-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    id bigint NOT NULL,
    login text NOT NULL,
    password text NOT NULL,
    name text NOT NULL,
    surname text NOT NULL,
    avatar text,
    "roleId" bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CourseCategory"
(
    id bigint NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."CourseCategory"
    IS 'Категория курса: математика, физика, языки и тд';

CREATE TABLE IF NOT EXISTS public."Course"
(
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "categoryId" bigint NOT NULL,
    "authorId" bigint NOT NULL,
    picture text,
    "isPublished" boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Module"
(
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "courseId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ModulePassed"
(
    id bigint NOT NULL,
    "moduleId" bigint NOT NULL,
    "isPassed" boolean NOT NULL,
    "userId" bigint NOT NULL,
    "datePassed" date,
    PRIMARY KEY (id),
    UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS public."CourseEnrollment"
(
    id bigint NOT NULL,
    "dateStarted" date NOT NULL,
    "dateEnded" date,
    "courseId" bigint NOT NULL,
    "userId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Topic"
(
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "moduleId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TopicContent"
(
    id bigint NOT NULL,
    description text NOT NULL,
    file text NOT NULL,
    "topicId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Test"
(
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "durationInMinutes" bigint NOT NULL,
    "moduleId" bigint,
    "courseId" bigint,
    PRIMARY KEY (id),
    UNIQUE ("courseId")
);

CREATE TABLE IF NOT EXISTS public."Question"
(
    id bigint NOT NULL,
    text text NOT NULL,
    picture text,
    "complexityPoints" bigint NOT NULL,
    "testId" bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Question"
    ADD COLUMN IF NOT EXISTS "questionType" text NOT NULL DEFAULT 'test';

ALTER TABLE IF EXISTS public."Question"
    ADD COLUMN IF NOT EXISTS "topicId" bigint;

CREATE TABLE IF NOT EXISTS public."Answer"
(
    id bigint NOT NULL,
    "isCorrect" boolean NOT NULL,
    text text NOT NULL,
    "questionId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TestResult"
(
    id bigint NOT NULL,
    "scoreInPoints" bigint NOT NULL,
    "isPassed" boolean NOT NULL,
    "durationInMinutes" bigint NOT NULL,
    result bigint NOT NULL,
    "testId" bigint NOT NULL,
    "userId" bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."UserAnswer"
(
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "testResultId" bigint NOT NULL,
    "questionId" bigint NOT NULL,
    "isCorrect" boolean NOT NULL,
    "timeSpentInMinutes" bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."UserModuleKnowledge"
(
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "moduleId" bigint NOT NULL,
    knowledge double precision NOT NULL DEFAULT 0.0,
    "lastUpdated" date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."UserCourseKnowledge"
(
    id bigint NOT NULL,
    "userId" bigint NOT NULL,
    "courseId" bigint NOT NULL,
    knowledge double precision NOT NULL DEFAULT 0.0,
    "lastUpdated" date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    id bigint NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Permissions"
(
    id bigint NOT NULL,
    action text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."RolePermissions"
(
    id bigint NOT NULL,
    "roleId" bigint NOT NULL,
    "permissionId" bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."User"
    ADD FOREIGN KEY ("roleId")
    REFERENCES public."Roles" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Course"
    ADD FOREIGN KEY ("categoryId")
    REFERENCES public."CourseCategory" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Course"
    ADD FOREIGN KEY ("authorId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Module"
    ADD FOREIGN KEY ("courseId")
    REFERENCES public."Course" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ModulePassed"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ModulePassed"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Module" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CourseEnrollment"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CourseEnrollment"
    ADD FOREIGN KEY ("courseId")
    REFERENCES public."Course" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Topic"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Module" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TopicContent"
    ADD FOREIGN KEY ("topicId")
    REFERENCES public."Topic" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Test"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Module" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Test"
    ADD FOREIGN KEY ("courseId")
    REFERENCES public."Course" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Question"
    ADD FOREIGN KEY ("testId")
    REFERENCES public."Test" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Answer"
    ADD FOREIGN KEY ("questionId")
    REFERENCES public."Question" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Question"
    ADD FOREIGN KEY ("topicId")
    REFERENCES public."Topic" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserAnswer"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserAnswer"
    ADD FOREIGN KEY ("testResultId")
    REFERENCES public."TestResult" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserAnswer"
    ADD FOREIGN KEY ("questionId")
    REFERENCES public."Question" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserModuleKnowledge"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserModuleKnowledge"
    ADD FOREIGN KEY ("moduleId")
    REFERENCES public."Module" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserCourseKnowledge"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."UserCourseKnowledge"
    ADD FOREIGN KEY ("courseId")
    REFERENCES public."Course" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TestResult"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TestResult"
    ADD FOREIGN KEY ("testId")
    REFERENCES public."Test" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RolePermissions"
    ADD FOREIGN KEY ("roleId")
    REFERENCES public."Roles" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RolePermissions"
    ADD FOREIGN KEY ("permissionId")
    REFERENCES public."Permissions" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
