/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CourseCategoryCreate from '../model/CourseCategoryCreate';
import CourseCategoryRead from '../model/CourseCategoryRead';
import CourseEnrollmentRead from '../model/CourseEnrollmentRead';
import PermissionCreate from '../model/PermissionCreate';
import PermissionRead from '../model/PermissionRead';
import RoleCreate from '../model/RoleCreate';
import RolePermissionCreate from '../model/RolePermissionCreate';
import RolePermissionRead from '../model/RolePermissionRead';
import RoleRead from '../model/RoleRead';
import TestResultRead from '../model/TestResultRead';
import UserAnswerRead from '../model/UserAnswerRead';
import UserCourseKnowledgeCreate from '../model/UserCourseKnowledgeCreate';
import UserCourseKnowledgeRead from '../model/UserCourseKnowledgeRead';
import UserModuleKnowledgeCreate from '../model/UserModuleKnowledgeCreate';
import UserModuleKnowledgeRead from '../model/UserModuleKnowledgeRead';

/**
* Full service.
* @module api/FullApi
* @version 0.1.0
*/
export default class FullApi {

    /**
    * Constructs a new FullApi. 
    * @alias module:api/FullApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Admin Create Course Knowledge
     * @param {module:model/UserCourseKnowledgeCreate} userCourseKnowledgeCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserCourseKnowledgeRead} and HTTP response
     */
    adminCreateCourseKnowledgeFullAdminCourseKnowledgePostWithHttpInfo(userCourseKnowledgeCreate) {
      let postBody = userCourseKnowledgeCreate;
      // verify the required parameter 'userCourseKnowledgeCreate' is set
      if (userCourseKnowledgeCreate === undefined || userCourseKnowledgeCreate === null) {
        throw new Error("Missing the required parameter 'userCourseKnowledgeCreate' when calling adminCreateCourseKnowledgeFullAdminCourseKnowledgePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserCourseKnowledgeRead;
      return this.apiClient.callApi(
        '/full/admin/course-knowledge', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Admin Create Course Knowledge
     * @param {module:model/UserCourseKnowledgeCreate} userCourseKnowledgeCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserCourseKnowledgeRead}
     */
    adminCreateCourseKnowledgeFullAdminCourseKnowledgePost(userCourseKnowledgeCreate) {
      return this.adminCreateCourseKnowledgeFullAdminCourseKnowledgePostWithHttpInfo(userCourseKnowledgeCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать/обновить UserModuleKnowledge
     * @param {module:model/UserModuleKnowledgeCreate} userModuleKnowledgeCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserModuleKnowledgeRead} and HTTP response
     */
    adminCreateModuleKnowledgeFullAdminModuleKnowledgePostWithHttpInfo(userModuleKnowledgeCreate) {
      let postBody = userModuleKnowledgeCreate;
      // verify the required parameter 'userModuleKnowledgeCreate' is set
      if (userModuleKnowledgeCreate === undefined || userModuleKnowledgeCreate === null) {
        throw new Error("Missing the required parameter 'userModuleKnowledgeCreate' when calling adminCreateModuleKnowledgeFullAdminModuleKnowledgePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserModuleKnowledgeRead;
      return this.apiClient.callApi(
        '/full/admin/module-knowledge', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать/обновить UserModuleKnowledge
     * @param {module:model/UserModuleKnowledgeCreate} userModuleKnowledgeCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserModuleKnowledgeRead}
     */
    adminCreateModuleKnowledgeFullAdminModuleKnowledgePost(userModuleKnowledgeCreate) {
      return this.adminCreateModuleKnowledgeFullAdminModuleKnowledgePostWithHttpInfo(userModuleKnowledgeCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить ответ пользователя
     * @param {Number} uaId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminDeleteAnswerFullAdminAnswersUaIdDeleteWithHttpInfo(uaId) {
      let postBody = null;
      // verify the required parameter 'uaId' is set
      if (uaId === undefined || uaId === null) {
        throw new Error("Missing the required parameter 'uaId' when calling adminDeleteAnswerFullAdminAnswersUaIdDelete");
      }

      let pathParams = {
        'ua_id': uaId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/answers/{ua_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить ответ пользователя
     * @param {Number} uaId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminDeleteAnswerFullAdminAnswersUaIdDelete(uaId) {
      return this.adminDeleteAnswerFullAdminAnswersUaIdDeleteWithHttpInfo(uaId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить запись на курс
     * Удаляет запись студента на курс. Доступно только администраторам.
     * @param {Number} enrollId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminDeleteEnrollmentFullAdminEnrollmentsEnrollIdDeleteWithHttpInfo(enrollId) {
      let postBody = null;
      // verify the required parameter 'enrollId' is set
      if (enrollId === undefined || enrollId === null) {
        throw new Error("Missing the required parameter 'enrollId' when calling adminDeleteEnrollmentFullAdminEnrollmentsEnrollIdDelete");
      }

      let pathParams = {
        'enroll_id': enrollId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/enrollments/{enroll_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить запись на курс
     * Удаляет запись студента на курс. Доступно только администраторам.
     * @param {Number} enrollId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminDeleteEnrollmentFullAdminEnrollmentsEnrollIdDelete(enrollId) {
      return this.adminDeleteEnrollmentFullAdminEnrollmentsEnrollIdDeleteWithHttpInfo(enrollId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить ответ пользователя
     * @param {Number} uaId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserAnswerRead} and HTTP response
     */
    adminGetAnswerFullAdminAnswersUaIdGetWithHttpInfo(uaId) {
      let postBody = null;
      // verify the required parameter 'uaId' is set
      if (uaId === undefined || uaId === null) {
        throw new Error("Missing the required parameter 'uaId' when calling adminGetAnswerFullAdminAnswersUaIdGet");
      }

      let pathParams = {
        'ua_id': uaId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserAnswerRead;
      return this.apiClient.callApi(
        '/full/admin/answers/{ua_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить ответ пользователя
     * @param {Number} uaId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserAnswerRead}
     */
    adminGetAnswerFullAdminAnswersUaIdGet(uaId) {
      return this.adminGetAnswerFullAdminAnswersUaIdGetWithHttpInfo(uaId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Admin Get Course Knowledge
     * @param {Number} uckId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserCourseKnowledgeRead} and HTTP response
     */
    adminGetCourseKnowledgeFullAdminCourseKnowledgeUckIdGetWithHttpInfo(uckId) {
      let postBody = null;
      // verify the required parameter 'uckId' is set
      if (uckId === undefined || uckId === null) {
        throw new Error("Missing the required parameter 'uckId' when calling adminGetCourseKnowledgeFullAdminCourseKnowledgeUckIdGet");
      }

      let pathParams = {
        'uck_id': uckId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserCourseKnowledgeRead;
      return this.apiClient.callApi(
        '/full/admin/course-knowledge/{uck_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Admin Get Course Knowledge
     * @param {Number} uckId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserCourseKnowledgeRead}
     */
    adminGetCourseKnowledgeFullAdminCourseKnowledgeUckIdGet(uckId) {
      return this.adminGetCourseKnowledgeFullAdminCourseKnowledgeUckIdGetWithHttpInfo(uckId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить запись на курс
     * Возвращает данные конкретной записи на курс по идентификатору. Только для администраторов.
     * @param {Number} enrollId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminGetEnrollmentFullAdminEnrollmentsEnrollIdGetWithHttpInfo(enrollId) {
      let postBody = null;
      // verify the required parameter 'enrollId' is set
      if (enrollId === undefined || enrollId === null) {
        throw new Error("Missing the required parameter 'enrollId' when calling adminGetEnrollmentFullAdminEnrollmentsEnrollIdGet");
      }

      let pathParams = {
        'enroll_id': enrollId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/enrollments/{enroll_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить запись на курс
     * Возвращает данные конкретной записи на курс по идентификатору. Только для администраторов.
     * @param {Number} enrollId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminGetEnrollmentFullAdminEnrollmentsEnrollIdGet(enrollId) {
      return this.adminGetEnrollmentFullAdminEnrollmentsEnrollIdGetWithHttpInfo(enrollId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить UserModuleKnowledge
     * @param {Number} umkId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserModuleKnowledgeRead} and HTTP response
     */
    adminGetModuleKnowledgeFullAdminModuleKnowledgeUmkIdGetWithHttpInfo(umkId) {
      let postBody = null;
      // verify the required parameter 'umkId' is set
      if (umkId === undefined || umkId === null) {
        throw new Error("Missing the required parameter 'umkId' when calling adminGetModuleKnowledgeFullAdminModuleKnowledgeUmkIdGet");
      }

      let pathParams = {
        'umk_id': umkId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserModuleKnowledgeRead;
      return this.apiClient.callApi(
        '/full/admin/module-knowledge/{umk_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить UserModuleKnowledge
     * @param {Number} umkId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserModuleKnowledgeRead}
     */
    adminGetModuleKnowledgeFullAdminModuleKnowledgeUmkIdGet(umkId) {
      return this.adminGetModuleKnowledgeFullAdminModuleKnowledgeUmkIdGetWithHttpInfo(umkId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить статус прохождения модуля
     * Возвращает запись о прохождении модуля по идентификатору. Только для администраторов.
     * @param {Number} mpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminGetModulePassedFullAdminModulePassedMpIdGetWithHttpInfo(mpId) {
      let postBody = null;
      // verify the required parameter 'mpId' is set
      if (mpId === undefined || mpId === null) {
        throw new Error("Missing the required parameter 'mpId' when calling adminGetModulePassedFullAdminModulePassedMpIdGet");
      }

      let pathParams = {
        'mp_id': mpId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/module-passed/{mp_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить статус прохождения модуля
     * Возвращает запись о прохождении модуля по идентификатору. Только для администраторов.
     * @param {Number} mpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminGetModulePassedFullAdminModulePassedMpIdGet(mpId) {
      return this.adminGetModulePassedFullAdminModulePassedMpIdGetWithHttpInfo(mpId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список всех ответов
     * Возвращает все записи UserAnswer. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserAnswerRead>} and HTTP response
     */
    adminListAnswersFullAdminAnswersGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserAnswerRead];
      return this.apiClient.callApi(
        '/full/admin/answers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список всех ответов
     * Возвращает все записи UserAnswer. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserAnswerRead>}
     */
    adminListAnswersFullAdminAnswersGet() {
      return this.adminListAnswersFullAdminAnswersGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список знаний по курсам
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserCourseKnowledgeRead>} and HTTP response
     */
    adminListCourseKnowledgeFullAdminCourseKnowledgeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserCourseKnowledgeRead];
      return this.apiClient.callApi(
        '/full/admin/course-knowledge', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список знаний по курсам
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserCourseKnowledgeRead>}
     */
    adminListCourseKnowledgeFullAdminCourseKnowledgeGet() {
      return this.adminListCourseKnowledgeFullAdminCourseKnowledgeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список всех записей на курсы
     * Возвращает все записи студентов на курсы. Доступно только администраторам.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminListEnrollmentsFullAdminEnrollmentsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/enrollments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список всех записей на курсы
     * Возвращает все записи студентов на курсы. Доступно только администраторам.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminListEnrollmentsFullAdminEnrollmentsGet() {
      return this.adminListEnrollmentsFullAdminEnrollmentsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список знаний по модулям
     * Возвращает все записи UserModuleKnowledge. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserModuleKnowledgeRead>} and HTTP response
     */
    adminListModuleKnowledgeFullAdminModuleKnowledgeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserModuleKnowledgeRead];
      return this.apiClient.callApi(
        '/full/admin/module-knowledge', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список знаний по модулям
     * Возвращает все записи UserModuleKnowledge. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserModuleKnowledgeRead>}
     */
    adminListModuleKnowledgeFullAdminModuleKnowledgeGet() {
      return this.adminListModuleKnowledgeFullAdminModuleKnowledgeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список статусов прохождения модулей
     * Возвращает все записи о прохождении модулей пользователями. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    adminListModulePassedFullAdminModulePassedGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/module-passed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список статусов прохождения модулей
     * Возвращает все записи о прохождении модулей пользователями. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    adminListModulePassedFullAdminModulePassedGet() {
      return this.adminListModulePassedFullAdminModulePassedGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать категорию курса
     * Добавляет новую категорию курсов. Требуются права преподавателя.
     * @param {module:model/CourseCategoryCreate} courseCategoryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseCategoryRead} and HTTP response
     */
    createCategoryFullAdminCategoriesPostWithHttpInfo(courseCategoryCreate) {
      let postBody = courseCategoryCreate;
      // verify the required parameter 'courseCategoryCreate' is set
      if (courseCategoryCreate === undefined || courseCategoryCreate === null) {
        throw new Error("Missing the required parameter 'courseCategoryCreate' when calling createCategoryFullAdminCategoriesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CourseCategoryRead;
      return this.apiClient.callApi(
        '/full/admin/categories', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать категорию курса
     * Добавляет новую категорию курсов. Требуются права преподавателя.
     * @param {module:model/CourseCategoryCreate} courseCategoryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseCategoryRead}
     */
    createCategoryFullAdminCategoriesPost(courseCategoryCreate) {
      return this.createCategoryFullAdminCategoriesPostWithHttpInfo(courseCategoryCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать разрешение
     * Добавляет новое действие в систему разрешений. Только для администраторов.
     * @param {module:model/PermissionCreate} permissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PermissionRead} and HTTP response
     */
    createPermissionFullAdminPermissionsPostWithHttpInfo(permissionCreate) {
      let postBody = permissionCreate;
      // verify the required parameter 'permissionCreate' is set
      if (permissionCreate === undefined || permissionCreate === null) {
        throw new Error("Missing the required parameter 'permissionCreate' when calling createPermissionFullAdminPermissionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PermissionRead;
      return this.apiClient.callApi(
        '/full/admin/permissions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать разрешение
     * Добавляет новое действие в систему разрешений. Только для администраторов.
     * @param {module:model/PermissionCreate} permissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PermissionRead}
     */
    createPermissionFullAdminPermissionsPost(permissionCreate) {
      return this.createPermissionFullAdminPermissionsPostWithHttpInfo(permissionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать роль
     * Добавляет новую роль в систему. Требуются права администратора.
     * @param {module:model/RoleCreate} roleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RoleRead} and HTTP response
     */
    createRoleFullAdminRolesPostWithHttpInfo(roleCreate) {
      let postBody = roleCreate;
      // verify the required parameter 'roleCreate' is set
      if (roleCreate === undefined || roleCreate === null) {
        throw new Error("Missing the required parameter 'roleCreate' when calling createRoleFullAdminRolesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoleRead;
      return this.apiClient.callApi(
        '/full/admin/roles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать роль
     * Добавляет новую роль в систему. Требуются права администратора.
     * @param {module:model/RoleCreate} roleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RoleRead}
     */
    createRoleFullAdminRolesPost(roleCreate) {
      return this.createRoleFullAdminRolesPostWithHttpInfo(roleCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Назначить разрешение роли
     * Создает связь между ролью и разрешением. Доступно только администраторам.
     * @param {module:model/RolePermissionCreate} rolePermissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RolePermissionRead} and HTTP response
     */
    createRolePermissionFullAdminRolePermissionsPostWithHttpInfo(rolePermissionCreate) {
      let postBody = rolePermissionCreate;
      // verify the required parameter 'rolePermissionCreate' is set
      if (rolePermissionCreate === undefined || rolePermissionCreate === null) {
        throw new Error("Missing the required parameter 'rolePermissionCreate' when calling createRolePermissionFullAdminRolePermissionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RolePermissionRead;
      return this.apiClient.callApi(
        '/full/admin/role-permissions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Назначить разрешение роли
     * Создает связь между ролью и разрешением. Доступно только администраторам.
     * @param {module:model/RolePermissionCreate} rolePermissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RolePermissionRead}
     */
    createRolePermissionFullAdminRolePermissionsPost(rolePermissionCreate) {
      return this.createRolePermissionFullAdminRolePermissionsPostWithHttpInfo(rolePermissionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить категорию курса
     * Удаляет категорию курсов по идентификатору. Требуются права преподавателя.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteCategoryFullAdminCategoriesCatIdDeleteWithHttpInfo(catId) {
      let postBody = null;
      // verify the required parameter 'catId' is set
      if (catId === undefined || catId === null) {
        throw new Error("Missing the required parameter 'catId' when calling deleteCategoryFullAdminCategoriesCatIdDelete");
      }

      let pathParams = {
        'cat_id': catId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/categories/{cat_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить категорию курса
     * Удаляет категорию курсов по идентификатору. Требуются права преподавателя.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteCategoryFullAdminCategoriesCatIdDelete(catId) {
      return this.deleteCategoryFullAdminCategoriesCatIdDeleteWithHttpInfo(catId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить разрешение
     * Удаляет разрешение из системы. Только для администраторов.
     * @param {Number} permId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deletePermissionFullAdminPermissionsPermIdDeleteWithHttpInfo(permId) {
      let postBody = null;
      // verify the required parameter 'permId' is set
      if (permId === undefined || permId === null) {
        throw new Error("Missing the required parameter 'permId' when calling deletePermissionFullAdminPermissionsPermIdDelete");
      }

      let pathParams = {
        'perm_id': permId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/permissions/{perm_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить разрешение
     * Удаляет разрешение из системы. Только для администраторов.
     * @param {Number} permId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deletePermissionFullAdminPermissionsPermIdDelete(permId) {
      return this.deletePermissionFullAdminPermissionsPermIdDeleteWithHttpInfo(permId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить роль
     * Удаляет роль из системы. Требуются права администратора.
     * @param {Number} roleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteRoleFullAdminRolesRoleIdDeleteWithHttpInfo(roleId) {
      let postBody = null;
      // verify the required parameter 'roleId' is set
      if (roleId === undefined || roleId === null) {
        throw new Error("Missing the required parameter 'roleId' when calling deleteRoleFullAdminRolesRoleIdDelete");
      }

      let pathParams = {
        'role_id': roleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/roles/{role_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить роль
     * Удаляет роль из системы. Требуются права администратора.
     * @param {Number} roleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteRoleFullAdminRolesRoleIdDelete(roleId) {
      return this.deleteRoleFullAdminRolesRoleIdDeleteWithHttpInfo(roleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить назначение разрешения
     * Удаляет связь роли и разрешения. Только для администраторов.
     * @param {Number} rpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteRolePermissionFullAdminRolePermissionsRpIdDeleteWithHttpInfo(rpId) {
      let postBody = null;
      // verify the required parameter 'rpId' is set
      if (rpId === undefined || rpId === null) {
        throw new Error("Missing the required parameter 'rpId' when calling deleteRolePermissionFullAdminRolePermissionsRpIdDelete");
      }

      let pathParams = {
        'rp_id': rpId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/admin/role-permissions/{rp_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить назначение разрешения
     * Удаляет связь роли и разрешения. Только для администраторов.
     * @param {Number} rpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteRolePermissionFullAdminRolePermissionsRpIdDelete(rpId) {
      return this.deleteRolePermissionFullAdminRolePermissionsRpIdDeleteWithHttpInfo(rpId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Записаться на курс
     * Создает запись студента на опубликованный курс.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseEnrollmentRead} and HTTP response
     */
    enrollCourseFullCoursesCourseIdEnrollPostWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling enrollCourseFullCoursesCourseIdEnrollPost");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CourseEnrollmentRead;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/enroll', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Записаться на курс
     * Создает запись студента на опубликованный курс.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseEnrollmentRead}
     */
    enrollCourseFullCoursesCourseIdEnrollPost(courseId) {
      return this.enrollCourseFullCoursesCourseIdEnrollPostWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить категорию курса
     * Возвращает категорию по идентификатору или 404, если ее нет.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseCategoryRead} and HTTP response
     */
    getCategoryFullAdminCategoriesCatIdGetWithHttpInfo(catId) {
      let postBody = null;
      // verify the required parameter 'catId' is set
      if (catId === undefined || catId === null) {
        throw new Error("Missing the required parameter 'catId' when calling getCategoryFullAdminCategoriesCatIdGet");
      }

      let pathParams = {
        'cat_id': catId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CourseCategoryRead;
      return this.apiClient.callApi(
        '/full/admin/categories/{cat_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить категорию курса
     * Возвращает категорию по идентификатору или 404, если ее нет.
     * @param {Number} catId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseCategoryRead}
     */
    getCategoryFullAdminCategoriesCatIdGet(catId) {
      return this.getCategoryFullAdminCategoriesCatIdGetWithHttpInfo(catId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить разрешение
     * Возвращает разрешение по идентификатору. Только для администраторов.
     * @param {Number} permId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PermissionRead} and HTTP response
     */
    getPermissionFullAdminPermissionsPermIdGetWithHttpInfo(permId) {
      let postBody = null;
      // verify the required parameter 'permId' is set
      if (permId === undefined || permId === null) {
        throw new Error("Missing the required parameter 'permId' when calling getPermissionFullAdminPermissionsPermIdGet");
      }

      let pathParams = {
        'perm_id': permId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PermissionRead;
      return this.apiClient.callApi(
        '/full/admin/permissions/{perm_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить разрешение
     * Возвращает разрешение по идентификатору. Только для администраторов.
     * @param {Number} permId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PermissionRead}
     */
    getPermissionFullAdminPermissionsPermIdGet(permId) {
      return this.getPermissionFullAdminPermissionsPermIdGetWithHttpInfo(permId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить результат теста
     * Возвращает результат теста, если пользователь — владелец, автор курса или администратор.
     * @param {Number} resultId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestResultRead} and HTTP response
     */
    getResultFullResultsResultIdGetWithHttpInfo(resultId) {
      let postBody = null;
      // verify the required parameter 'resultId' is set
      if (resultId === undefined || resultId === null) {
        throw new Error("Missing the required parameter 'resultId' when calling getResultFullResultsResultIdGet");
      }

      let pathParams = {
        'result_id': resultId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TestResultRead;
      return this.apiClient.callApi(
        '/full/results/{result_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить результат теста
     * Возвращает результат теста, если пользователь — владелец, автор курса или администратор.
     * @param {Number} resultId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestResultRead}
     */
    getResultFullResultsResultIdGet(resultId) {
      return this.getResultFullResultsResultIdGetWithHttpInfo(resultId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить роль
     * Возвращает данные роли по идентификатору. Только для администраторов.
     * @param {Number} roleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RoleRead} and HTTP response
     */
    getRoleFullAdminRolesRoleIdGetWithHttpInfo(roleId) {
      let postBody = null;
      // verify the required parameter 'roleId' is set
      if (roleId === undefined || roleId === null) {
        throw new Error("Missing the required parameter 'roleId' when calling getRoleFullAdminRolesRoleIdGet");
      }

      let pathParams = {
        'role_id': roleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RoleRead;
      return this.apiClient.callApi(
        '/full/admin/roles/{role_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить роль
     * Возвращает данные роли по идентификатору. Только для администраторов.
     * @param {Number} roleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RoleRead}
     */
    getRoleFullAdminRolesRoleIdGet(roleId) {
      return this.getRoleFullAdminRolesRoleIdGetWithHttpInfo(roleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить назначенное разрешение
     * Возвращает конкретную связь роли и разрешения по идентификатору. Только для администраторов.
     * @param {Number} rpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RolePermissionRead} and HTTP response
     */
    getRolePermissionFullAdminRolePermissionsRpIdGetWithHttpInfo(rpId) {
      let postBody = null;
      // verify the required parameter 'rpId' is set
      if (rpId === undefined || rpId === null) {
        throw new Error("Missing the required parameter 'rpId' when calling getRolePermissionFullAdminRolePermissionsRpIdGet");
      }

      let pathParams = {
        'rp_id': rpId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RolePermissionRead;
      return this.apiClient.callApi(
        '/full/admin/role-permissions/{rp_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить назначенное разрешение
     * Возвращает конкретную связь роли и разрешения по идентификатору. Только для администраторов.
     * @param {Number} rpId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RolePermissionRead}
     */
    getRolePermissionFullAdminRolePermissionsRpIdGet(rpId) {
      return this.getRolePermissionFullAdminRolePermissionsRpIdGetWithHttpInfo(rpId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить категории курсов
     * Возвращает постраничный список категорий курсов.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 100)] 
     * @param {Number} [offset = 0)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CourseCategoryRead>} and HTTP response
     */
    listCategoriesFullAdminCategoriesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseCategoryRead];
      return this.apiClient.callApi(
        '/full/admin/categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить категории курсов
     * Возвращает постраничный список категорий курсов.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit  (default to 100)
     * @param {Number} opts.offset  (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CourseCategoryRead>}
     */
    listCategoriesFullAdminCategoriesGet(opts) {
      return this.listCategoriesFullAdminCategoriesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список разрешений
     * Возвращает все зарегистрированные разрешения. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PermissionRead>} and HTTP response
     */
    listPermissionsFullAdminPermissionsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PermissionRead];
      return this.apiClient.callApi(
        '/full/admin/permissions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список разрешений
     * Возвращает все зарегистрированные разрешения. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PermissionRead>}
     */
    listPermissionsFullAdminPermissionsGet() {
      return this.listPermissionsFullAdminPermissionsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список назначенных разрешений
     * Возвращает все связи ролей и разрешений. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/RolePermissionRead>} and HTTP response
     */
    listRolePermissionsFullAdminRolePermissionsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [RolePermissionRead];
      return this.apiClient.callApi(
        '/full/admin/role-permissions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список назначенных разрешений
     * Возвращает все связи ролей и разрешений. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/RolePermissionRead>}
     */
    listRolePermissionsFullAdminRolePermissionsGet() {
      return this.listRolePermissionsFullAdminRolePermissionsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список ролей
     * Возвращает все доступные роли. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/RoleRead>} and HTTP response
     */
    listRolesFullAdminRolesGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [RoleRead];
      return this.apiClient.callApi(
        '/full/admin/roles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список ролей
     * Возвращает все доступные роли. Только для администраторов.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/RoleRead>}
     */
    listRolesFullAdminRolesGet() {
      return this.listRolesFullAdminRolesGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Мои ответы на вопросы
     * Возвращает все сохранённые ответы текущего пользователя.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserAnswerRead>} and HTTP response
     */
    myAnswersFullAnswersMeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserAnswerRead];
      return this.apiClient.callApi(
        '/full/answers/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Мои ответы на вопросы
     * Возвращает все сохранённые ответы текущего пользователя.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserAnswerRead>}
     */
    myAnswersFullAnswersMeGet() {
      return this.myAnswersFullAnswersMeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Уровень знаний по курсам (мои)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserCourseKnowledgeRead>} and HTTP response
     */
    myCourseKnowledgeFullMeCoursesKnowledgeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserCourseKnowledgeRead];
      return this.apiClient.callApi(
        '/full/me/courses/knowledge', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Уровень знаний по курсам (мои)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserCourseKnowledgeRead>}
     */
    myCourseKnowledgeFullMeCoursesKnowledgeGet() {
      return this.myCourseKnowledgeFullMeCoursesKnowledgeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Уровень знаний по модулям (мои)
     * Возвращает агрегированные знания пользователя по модулям.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserModuleKnowledgeRead>} and HTTP response
     */
    myModuleKnowledgeFullMeModulesKnowledgeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserModuleKnowledgeRead];
      return this.apiClient.callApi(
        '/full/me/modules/knowledge', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Уровень знаний по модулям (мои)
     * Возвращает агрегированные знания пользователя по модулям.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserModuleKnowledgeRead>}
     */
    myModuleKnowledgeFullMeModulesKnowledgeGet() {
      return this.myModuleKnowledgeFullMeModulesKnowledgeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Мои результаты тестов
     * Возвращает результаты тестов для текущего пользователя.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TestResultRead>} and HTTP response
     */
    myResultsFullResultsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TestResultRead];
      return this.apiClient.callApi(
        '/full/results', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Мои результаты тестов
     * Возвращает результаты тестов для текущего пользователя.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TestResultRead>}
     */
    myResultsFullResultsGet() {
      return this.myResultsFullResultsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Сдать тест
     * Принимает ответы пользователя, проверяет их и сохраняет результат попытки.
     * @param {Number} testId 
     * @param {Object.<String, {String: Object}>} requestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    submitTestFullTestsTestIdSubmitPostWithHttpInfo(testId, requestBody) {
      let postBody = requestBody;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling submitTestFullTestsTestIdSubmitPost");
      }
      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling submitTestFullTestsTestIdSubmitPost");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/tests/{test_id}/submit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Сдать тест
     * Принимает ответы пользователя, проверяет их и сохраняет результат попытки.
     * @param {Number} testId 
     * @param {Object.<String, {String: Object}>} requestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    submitTestFullTestsTestIdSubmitPost(testId, requestBody) {
      return this.submitTestFullTestsTestIdSubmitPostWithHttpInfo(testId, requestBody)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Уровень знаний конкретного студента по курсу (для преподавателя)
     * @param {Number} courseId 
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserCourseKnowledgeRead} and HTTP response
     */
    teacherGetStudentCourseKnowledgeFullTeacherCourseCourseIdKnowledgeUserIdGetWithHttpInfo(courseId, userId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling teacherGetStudentCourseKnowledgeFullTeacherCourseCourseIdKnowledgeUserIdGet");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling teacherGetStudentCourseKnowledgeFullTeacherCourseCourseIdKnowledgeUserIdGet");
      }

      let pathParams = {
        'course_id': courseId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserCourseKnowledgeRead;
      return this.apiClient.callApi(
        '/full/teacher/course/{course_id}/knowledge/{user_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Уровень знаний конкретного студента по курсу (для преподавателя)
     * @param {Number} courseId 
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserCourseKnowledgeRead}
     */
    teacherGetStudentCourseKnowledgeFullTeacherCourseCourseIdKnowledgeUserIdGet(courseId, userId) {
      return this.teacherGetStudentCourseKnowledgeFullTeacherCourseCourseIdKnowledgeUserIdGetWithHttpInfo(courseId, userId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Уровень знаний студента по модулю (для преподавателя)
     * @param {Number} moduleId 
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserModuleKnowledgeRead} and HTTP response
     */
    teacherGetStudentModuleKnowledgeFullTeacherModuleModuleIdKnowledgeUserIdGetWithHttpInfo(moduleId, userId) {
      let postBody = null;
      // verify the required parameter 'moduleId' is set
      if (moduleId === undefined || moduleId === null) {
        throw new Error("Missing the required parameter 'moduleId' when calling teacherGetStudentModuleKnowledgeFullTeacherModuleModuleIdKnowledgeUserIdGet");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling teacherGetStudentModuleKnowledgeFullTeacherModuleModuleIdKnowledgeUserIdGet");
      }

      let pathParams = {
        'module_id': moduleId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserModuleKnowledgeRead;
      return this.apiClient.callApi(
        '/full/teacher/module/{module_id}/knowledge/{user_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Уровень знаний студента по модулю (для преподавателя)
     * @param {Number} moduleId 
     * @param {Number} userId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserModuleKnowledgeRead}
     */
    teacherGetStudentModuleKnowledgeFullTeacherModuleModuleIdKnowledgeUserIdGet(moduleId, userId) {
      return this.teacherGetStudentModuleKnowledgeFullTeacherModuleModuleIdKnowledgeUserIdGetWithHttpInfo(moduleId, userId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Статусы знаний студентов по курсу (для преподавателя)
     * Возвращает уровень знаний всех студентов по курсу. Доступно только автору курса (преподавателю).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserCourseKnowledgeRead>} and HTTP response
     */
    teacherListStudentsCourseKnowledgeFullTeacherCourseCourseIdStudentsKnowledgeGetWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling teacherListStudentsCourseKnowledgeFullTeacherCourseCourseIdStudentsKnowledgeGet");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [UserCourseKnowledgeRead];
      return this.apiClient.callApi(
        '/full/teacher/course/{course_id}/students/knowledge', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Статусы знаний студентов по курсу (для преподавателя)
     * Возвращает уровень знаний всех студентов по курсу. Доступно только автору курса (преподавателю).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserCourseKnowledgeRead>}
     */
    teacherListStudentsCourseKnowledgeFullTeacherCourseCourseIdStudentsKnowledgeGet(courseId) {
      return this.teacherListStudentsCourseKnowledgeFullTeacherCourseCourseIdStudentsKnowledgeGetWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Отменить запись на курс
     * Удаляет запись студента на курс, если она существует.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    unenrollCourseFullCoursesCourseIdEnrollDeleteWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling unenrollCourseFullCoursesCourseIdEnrollDelete");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/enroll', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Отменить запись на курс
     * Удаляет запись студента на курс, если она существует.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    unenrollCourseFullCoursesCourseIdEnrollDelete(courseId) {
      return this.unenrollCourseFullCoursesCourseIdEnrollDeleteWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить категорию курса
     * Изменяет название существующей категории. Требуются права преподавателя.
     * @param {Number} catId 
     * @param {module:model/CourseCategoryCreate} courseCategoryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseCategoryRead} and HTTP response
     */
    updateCategoryFullAdminCategoriesCatIdPutWithHttpInfo(catId, courseCategoryCreate) {
      let postBody = courseCategoryCreate;
      // verify the required parameter 'catId' is set
      if (catId === undefined || catId === null) {
        throw new Error("Missing the required parameter 'catId' when calling updateCategoryFullAdminCategoriesCatIdPut");
      }
      // verify the required parameter 'courseCategoryCreate' is set
      if (courseCategoryCreate === undefined || courseCategoryCreate === null) {
        throw new Error("Missing the required parameter 'courseCategoryCreate' when calling updateCategoryFullAdminCategoriesCatIdPut");
      }

      let pathParams = {
        'cat_id': catId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CourseCategoryRead;
      return this.apiClient.callApi(
        '/full/admin/categories/{cat_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить категорию курса
     * Изменяет название существующей категории. Требуются права преподавателя.
     * @param {Number} catId 
     * @param {module:model/CourseCategoryCreate} courseCategoryCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseCategoryRead}
     */
    updateCategoryFullAdminCategoriesCatIdPut(catId, courseCategoryCreate) {
      return this.updateCategoryFullAdminCategoriesCatIdPutWithHttpInfo(catId, courseCategoryCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить разрешение
     * Изменяет действие существующего разрешения. Только для администраторов.
     * @param {Number} permId 
     * @param {module:model/PermissionCreate} permissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PermissionRead} and HTTP response
     */
    updatePermissionFullAdminPermissionsPermIdPutWithHttpInfo(permId, permissionCreate) {
      let postBody = permissionCreate;
      // verify the required parameter 'permId' is set
      if (permId === undefined || permId === null) {
        throw new Error("Missing the required parameter 'permId' when calling updatePermissionFullAdminPermissionsPermIdPut");
      }
      // verify the required parameter 'permissionCreate' is set
      if (permissionCreate === undefined || permissionCreate === null) {
        throw new Error("Missing the required parameter 'permissionCreate' when calling updatePermissionFullAdminPermissionsPermIdPut");
      }

      let pathParams = {
        'perm_id': permId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PermissionRead;
      return this.apiClient.callApi(
        '/full/admin/permissions/{perm_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить разрешение
     * Изменяет действие существующего разрешения. Только для администраторов.
     * @param {Number} permId 
     * @param {module:model/PermissionCreate} permissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PermissionRead}
     */
    updatePermissionFullAdminPermissionsPermIdPut(permId, permissionCreate) {
      return this.updatePermissionFullAdminPermissionsPermIdPutWithHttpInfo(permId, permissionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить роль
     * Изменяет название роли. Доступно только администраторам.
     * @param {Number} roleId 
     * @param {module:model/RoleCreate} roleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RoleRead} and HTTP response
     */
    updateRoleFullAdminRolesRoleIdPutWithHttpInfo(roleId, roleCreate) {
      let postBody = roleCreate;
      // verify the required parameter 'roleId' is set
      if (roleId === undefined || roleId === null) {
        throw new Error("Missing the required parameter 'roleId' when calling updateRoleFullAdminRolesRoleIdPut");
      }
      // verify the required parameter 'roleCreate' is set
      if (roleCreate === undefined || roleCreate === null) {
        throw new Error("Missing the required parameter 'roleCreate' when calling updateRoleFullAdminRolesRoleIdPut");
      }

      let pathParams = {
        'role_id': roleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RoleRead;
      return this.apiClient.callApi(
        '/full/admin/roles/{role_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить роль
     * Изменяет название роли. Доступно только администраторам.
     * @param {Number} roleId 
     * @param {module:model/RoleCreate} roleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RoleRead}
     */
    updateRoleFullAdminRolesRoleIdPut(roleId, roleCreate) {
      return this.updateRoleFullAdminRolesRoleIdPutWithHttpInfo(roleId, roleCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить назначение разрешения
     * Изменяет связь между ролью и разрешением. Только для администраторов.
     * @param {Number} rpId 
     * @param {module:model/RolePermissionCreate} rolePermissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RolePermissionRead} and HTTP response
     */
    updateRolePermissionFullAdminRolePermissionsRpIdPutWithHttpInfo(rpId, rolePermissionCreate) {
      let postBody = rolePermissionCreate;
      // verify the required parameter 'rpId' is set
      if (rpId === undefined || rpId === null) {
        throw new Error("Missing the required parameter 'rpId' when calling updateRolePermissionFullAdminRolePermissionsRpIdPut");
      }
      // verify the required parameter 'rolePermissionCreate' is set
      if (rolePermissionCreate === undefined || rolePermissionCreate === null) {
        throw new Error("Missing the required parameter 'rolePermissionCreate' when calling updateRolePermissionFullAdminRolePermissionsRpIdPut");
      }

      let pathParams = {
        'rp_id': rpId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RolePermissionRead;
      return this.apiClient.callApi(
        '/full/admin/role-permissions/{rp_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить назначение разрешения
     * Изменяет связь между ролью и разрешением. Только для администраторов.
     * @param {Number} rpId 
     * @param {module:model/RolePermissionCreate} rolePermissionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RolePermissionRead}
     */
    updateRolePermissionFullAdminRolePermissionsRpIdPut(rpId, rolePermissionCreate) {
      return this.updateRolePermissionFullAdminRolePermissionsRpIdPutWithHttpInfo(rpId, rolePermissionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
