/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AnswerCreate from '../model/AnswerCreate';
import AnswerRead from '../model/AnswerRead';
import CourseCreate from '../model/CourseCreate';
import CourseRead from '../model/CourseRead';
import ModuleCreate from '../model/ModuleCreate';
import ModuleRead from '../model/ModuleRead';
import QuestionCreate from '../model/QuestionCreate';
import QuestionRead from '../model/QuestionRead';
import TestCreate from '../model/TestCreate';
import TestRead from '../model/TestRead';
import TestResultRead from '../model/TestResultRead';
import TopicContentCreate from '../model/TopicContentCreate';
import TopicContentRead from '../model/TopicContentRead';
import TopicCreate from '../model/TopicCreate';
import TopicRead from '../model/TopicRead';

/**
* Teaching service.
* @module api/TeachingApi
* @version 0.1.0
*/
export default class TeachingApi {

    /**
    * Constructs a new TeachingApi. 
    * @alias module:api/TeachingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Создать ответ
     * Добавляет новый вариант ответа к вопросу теста. Доступно только автору курса.
     * @param {module:model/AnswerCreate} answerCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnswerRead} and HTTP response
     */
    createAnswerFullAnswersPostWithHttpInfo(answerCreate) {
      let postBody = answerCreate;
      // verify the required parameter 'answerCreate' is set
      if (answerCreate === undefined || answerCreate === null) {
        throw new Error("Missing the required parameter 'answerCreate' when calling createAnswerFullAnswersPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AnswerRead;
      return this.apiClient.callApi(
        '/full/answers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать ответ
     * Добавляет новый вариант ответа к вопросу теста. Доступно только автору курса.
     * @param {module:model/AnswerCreate} answerCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnswerRead}
     */
    createAnswerFullAnswersPost(answerCreate) {
      return this.createAnswerFullAnswersPostWithHttpInfo(answerCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать новый курс
     * Создает черновик курса и привязывает его к текущему преподавателю.
     * @param {module:model/CourseCreate} courseCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseRead} and HTTP response
     */
    createCourseFullCoursesPostWithHttpInfo(courseCreate) {
      let postBody = courseCreate;
      // verify the required parameter 'courseCreate' is set
      if (courseCreate === undefined || courseCreate === null) {
        throw new Error("Missing the required parameter 'courseCreate' when calling createCourseFullCoursesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CourseRead;
      return this.apiClient.callApi(
        '/full/courses', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать новый курс
     * Создает черновик курса и привязывает его к текущему преподавателю.
     * @param {module:model/CourseCreate} courseCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseRead}
     */
    createCourseFullCoursesPost(courseCreate) {
      return this.createCourseFullCoursesPostWithHttpInfo(courseCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать модуль
     * Добавляет новый модуль в существующий курс. Доступно только автору курса.
     * @param {module:model/ModuleCreate} moduleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ModuleRead} and HTTP response
     */
    createModuleFullModulesPostWithHttpInfo(moduleCreate) {
      let postBody = moduleCreate;
      // verify the required parameter 'moduleCreate' is set
      if (moduleCreate === undefined || moduleCreate === null) {
        throw new Error("Missing the required parameter 'moduleCreate' when calling createModuleFullModulesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ModuleRead;
      return this.apiClient.callApi(
        '/full/modules', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать модуль
     * Добавляет новый модуль в существующий курс. Доступно только автору курса.
     * @param {module:model/ModuleCreate} moduleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ModuleRead}
     */
    createModuleFullModulesPost(moduleCreate) {
      return this.createModuleFullModulesPostWithHttpInfo(moduleCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать вопрос
     * Добавляет вопрос к тесту. Доступно только автору курса.
     * @param {module:model/QuestionCreate} questionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/QuestionRead} and HTTP response
     */
    createQuestionFullQuestionsPostWithHttpInfo(questionCreate) {
      let postBody = questionCreate;
      // verify the required parameter 'questionCreate' is set
      if (questionCreate === undefined || questionCreate === null) {
        throw new Error("Missing the required parameter 'questionCreate' when calling createQuestionFullQuestionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = QuestionRead;
      return this.apiClient.callApi(
        '/full/questions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать вопрос
     * Добавляет вопрос к тесту. Доступно только автору курса.
     * @param {module:model/QuestionCreate} questionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/QuestionRead}
     */
    createQuestionFullQuestionsPost(questionCreate) {
      return this.createQuestionFullQuestionsPostWithHttpInfo(questionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать тест
     * Создает тест на уровне курса или модуля с проверкой уникальности и прав доступа.
     * @param {module:model/TestCreate} testCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestRead} and HTTP response
     */
    createTestFullTestsPostWithHttpInfo(testCreate) {
      let postBody = testCreate;
      // verify the required parameter 'testCreate' is set
      if (testCreate === undefined || testCreate === null) {
        throw new Error("Missing the required parameter 'testCreate' when calling createTestFullTestsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TestRead;
      return this.apiClient.callApi(
        '/full/tests', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать тест
     * Создает тест на уровне курса или модуля с проверкой уникальности и прав доступа.
     * @param {module:model/TestCreate} testCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestRead}
     */
    createTestFullTestsPost(testCreate) {
      return this.createTestFullTestsPostWithHttpInfo(testCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать материал темы (загрузка файла)
     * Загружает файл материала и создаёт запись TopicContent. Только автор курса.
     * @param {Number} topicId 
     * @param {Object} opts Optional parameters
     * @param {String} [description] 
     * @param {File} [file] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicContentRead} and HTTP response
     */
    createTopicContentFullTopicContentsPostWithHttpInfo(topicId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'topicId' is set
      if (topicId === undefined || topicId === null) {
        throw new Error("Missing the required parameter 'topicId' when calling createTopicContentFullTopicContentsPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'topicId': topicId,
        'description': opts['description']
      };
      let headerParams = {
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = TopicContentRead;
      return this.apiClient.callApi(
        '/full/topic-contents', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать материал темы (загрузка файла)
     * Загружает файл материала и создаёт запись TopicContent. Только автор курса.
     * @param {Number} topicId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.description 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicContentRead}
     */
    createTopicContentFullTopicContentsPost(topicId, opts) {
      return this.createTopicContentFullTopicContentsPostWithHttpInfo(topicId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать тему
     * Добавляет тему в выбранный модуль. Доступно только автору курса.
     * @param {module:model/TopicCreate} topicCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicRead} and HTTP response
     */
    createTopicFullTopicsPostWithHttpInfo(topicCreate) {
      let postBody = topicCreate;
      // verify the required parameter 'topicCreate' is set
      if (topicCreate === undefined || topicCreate === null) {
        throw new Error("Missing the required parameter 'topicCreate' when calling createTopicFullTopicsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TopicRead;
      return this.apiClient.callApi(
        '/full/topics', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать тему
     * Добавляет тему в выбранный модуль. Доступно только автору курса.
     * @param {module:model/TopicCreate} topicCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicRead}
     */
    createTopicFullTopicsPost(topicCreate) {
      return this.createTopicFullTopicsPostWithHttpInfo(topicCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить ответ
     * Удаляет вариант ответа из вопроса теста. Доступно только автору курса.
     * @param {Number} answerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteAnswerFullAnswersAnswerIdDeleteWithHttpInfo(answerId) {
      let postBody = null;
      // verify the required parameter 'answerId' is set
      if (answerId === undefined || answerId === null) {
        throw new Error("Missing the required parameter 'answerId' when calling deleteAnswerFullAnswersAnswerIdDelete");
      }

      let pathParams = {
        'answer_id': answerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/answers/{answer_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить ответ
     * Удаляет вариант ответа из вопроса теста. Доступно только автору курса.
     * @param {Number} answerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteAnswerFullAnswersAnswerIdDelete(answerId) {
      return this.deleteAnswerFullAnswersAnswerIdDeleteWithHttpInfo(answerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить курс
     * Удаляет курс целиком. Доступно только автору курса.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteCourseFullCoursesCourseIdDeleteWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling deleteCourseFullCoursesCourseIdDelete");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/courses/{course_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить курс
     * Удаляет курс целиком. Доступно только автору курса.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteCourseFullCoursesCourseIdDelete(courseId) {
      return this.deleteCourseFullCoursesCourseIdDeleteWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить картинку курса
     * Удаляет картинку курса (только автор курса).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteCoursePictureFullCoursesCourseIdPictureDeleteWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling deleteCoursePictureFullCoursesCourseIdPictureDelete");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/picture', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить картинку курса
     * Удаляет картинку курса (только автор курса).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteCoursePictureFullCoursesCourseIdPictureDelete(courseId) {
      return this.deleteCoursePictureFullCoursesCourseIdPictureDeleteWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить модуль
     * Удаляет модуль и все связанные записи. Доступно только автору курса.
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteModuleFullModulesModuleIdDeleteWithHttpInfo(moduleId) {
      let postBody = null;
      // verify the required parameter 'moduleId' is set
      if (moduleId === undefined || moduleId === null) {
        throw new Error("Missing the required parameter 'moduleId' when calling deleteModuleFullModulesModuleIdDelete");
      }

      let pathParams = {
        'module_id': moduleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/modules/{module_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить модуль
     * Удаляет модуль и все связанные записи. Доступно только автору курса.
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteModuleFullModulesModuleIdDelete(moduleId) {
      return this.deleteModuleFullModulesModuleIdDeleteWithHttpInfo(moduleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить вопрос
     * Удаляет вопрос теста. Доступно только автору курса.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteQuestionFullQuestionsQuestionIdDeleteWithHttpInfo(questionId) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling deleteQuestionFullQuestionsQuestionIdDelete");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/questions/{question_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить вопрос
     * Удаляет вопрос теста. Доступно только автору курса.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteQuestionFullQuestionsQuestionIdDelete(questionId) {
      return this.deleteQuestionFullQuestionsQuestionIdDeleteWithHttpInfo(questionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить картинку вопроса
     * Удаляет картинку вопроса (author или admin).
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteQuestionPictureFullQuestionsQuestionIdPictureDeleteWithHttpInfo(questionId) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling deleteQuestionPictureFullQuestionsQuestionIdPictureDelete");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/questions/{question_id}/picture', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить картинку вопроса
     * Удаляет картинку вопроса (author или admin).
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteQuestionPictureFullQuestionsQuestionIdPictureDelete(questionId) {
      return this.deleteQuestionPictureFullQuestionsQuestionIdPictureDeleteWithHttpInfo(questionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить тест
     * Удаляет тест. Доступно только автору соответствующего курса.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteTestFullTestsTestIdDeleteWithHttpInfo(testId) {
      let postBody = null;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling deleteTestFullTestsTestIdDelete");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/tests/{test_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить тест
     * Удаляет тест. Доступно только автору соответствующего курса.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteTestFullTestsTestIdDelete(testId) {
      return this.deleteTestFullTestsTestIdDeleteWithHttpInfo(testId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить материал темы
     * Удаляет материал и связанный файл. Доступно только автору курса.
     * @param {Number} contentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteTopicContentFullTopicContentsContentIdDeleteWithHttpInfo(contentId) {
      let postBody = null;
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling deleteTopicContentFullTopicContentsContentIdDelete");
      }

      let pathParams = {
        'content_id': contentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/topic-contents/{content_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить материал темы
     * Удаляет материал и связанный файл. Доступно только автору курса.
     * @param {Number} contentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteTopicContentFullTopicContentsContentIdDelete(contentId) {
      return this.deleteTopicContentFullTopicContentsContentIdDeleteWithHttpInfo(contentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить тему
     * Удаляет тему и связанные материалы. Доступно только автору курса.
     * @param {Number} topicId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    deleteTopicFullTopicsTopicIdDeleteWithHttpInfo(topicId) {
      let postBody = null;
      // verify the required parameter 'topicId' is set
      if (topicId === undefined || topicId === null) {
        throw new Error("Missing the required parameter 'topicId' when calling deleteTopicFullTopicsTopicIdDelete");
      }

      let pathParams = {
        'topic_id': topicId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/topics/{topic_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить тему
     * Удаляет тему и связанные материалы. Доступно только автору курса.
     * @param {Number} topicId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    deleteTopicFullTopicsTopicIdDelete(topicId) {
      return this.deleteTopicFullTopicsTopicIdDeleteWithHttpInfo(topicId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Скачать файл материала
     * Отдает файл материала темы после проверки прав доступа.
     * @param {Number} contentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    downloadTopicContentFullTopicContentsContentIdDownloadGetWithHttpInfo(contentId) {
      let postBody = null;
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling downloadTopicContentFullTopicContentsContentIdDownloadGet");
      }

      let pathParams = {
        'content_id': contentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/topic-contents/{content_id}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Скачать файл материала
     * Отдает файл материала темы после проверки прав доступа.
     * @param {Number} contentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    downloadTopicContentFullTopicContentsContentIdDownloadGet(contentId) {
      return this.downloadTopicContentFullTopicContentsContentIdDownloadGetWithHttpInfo(contentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить ответ
     * Возвращает ответ по идентификатору.
     * @param {Number} answerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnswerRead} and HTTP response
     */
    getAnswerFullAnswersAnswerIdGetWithHttpInfo(answerId) {
      let postBody = null;
      // verify the required parameter 'answerId' is set
      if (answerId === undefined || answerId === null) {
        throw new Error("Missing the required parameter 'answerId' when calling getAnswerFullAnswersAnswerIdGet");
      }

      let pathParams = {
        'answer_id': answerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AnswerRead;
      return this.apiClient.callApi(
        '/full/answers/{answer_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить ответ
     * Возвращает ответ по идентификатору.
     * @param {Number} answerId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnswerRead}
     */
    getAnswerFullAnswersAnswerIdGet(answerId) {
      return this.getAnswerFullAnswersAnswerIdGetWithHttpInfo(answerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить курс по идентификатору
     * Возвращает полную информацию о конкретном курсе по его идентификатору.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseRead} and HTTP response
     */
    getCourseFullCoursesCourseIdGetWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling getCourseFullCoursesCourseIdGet");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CourseRead;
      return this.apiClient.callApi(
        '/full/courses/{course_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить курс по идентификатору
     * Возвращает полную информацию о конкретном курсе по его идентификатору.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseRead}
     */
    getCourseFullCoursesCourseIdGet(courseId) {
      return this.getCourseFullCoursesCourseIdGetWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить картинку курса по id
     * Возвращает файл картинки, привязанной к курсу (по id курса).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCoursePictureFullCoursesCourseIdPictureGetWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling getCoursePictureFullCoursesCourseIdPictureGet");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/picture', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить картинку курса по id
     * Возвращает файл картинки, привязанной к курсу (по id курса).
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCoursePictureFullCoursesCourseIdPictureGet(courseId) {
      return this.getCoursePictureFullCoursesCourseIdPictureGetWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить модуль по идентификатору
     * Возвращает данные модуля вместе с привязкой к курсу.
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ModuleRead} and HTTP response
     */
    getModuleFullModulesModuleIdGetWithHttpInfo(moduleId) {
      let postBody = null;
      // verify the required parameter 'moduleId' is set
      if (moduleId === undefined || moduleId === null) {
        throw new Error("Missing the required parameter 'moduleId' when calling getModuleFullModulesModuleIdGet");
      }

      let pathParams = {
        'module_id': moduleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModuleRead;
      return this.apiClient.callApi(
        '/full/modules/{module_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить модуль по идентификатору
     * Возвращает данные модуля вместе с привязкой к курсу.
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ModuleRead}
     */
    getModuleFullModulesModuleIdGet(moduleId) {
      return this.getModuleFullModulesModuleIdGetWithHttpInfo(moduleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить вопрос
     * Возвращает вопрос теста по идентификатору.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/QuestionRead} and HTTP response
     */
    getQuestionFullQuestionsQuestionIdGetWithHttpInfo(questionId) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling getQuestionFullQuestionsQuestionIdGet");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = QuestionRead;
      return this.apiClient.callApi(
        '/full/questions/{question_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить вопрос
     * Возвращает вопрос теста по идентификатору.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/QuestionRead}
     */
    getQuestionFullQuestionsQuestionIdGet(questionId) {
      return this.getQuestionFullQuestionsQuestionIdGetWithHttpInfo(questionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить картинку вопроса по id
     * Возвращает картинку, привязанную к вопросу.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getQuestionPictureFullQuestionsQuestionIdPictureGetWithHttpInfo(questionId) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling getQuestionPictureFullQuestionsQuestionIdPictureGet");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/questions/{question_id}/picture', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить картинку вопроса по id
     * Возвращает картинку, привязанную к вопросу.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getQuestionPictureFullQuestionsQuestionIdPictureGet(questionId) {
      return this.getQuestionPictureFullQuestionsQuestionIdPictureGetWithHttpInfo(questionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить тест
     * Возвращает тест по идентификатору.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestRead} and HTTP response
     */
    getTestFullTestsTestIdGetWithHttpInfo(testId) {
      let postBody = null;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling getTestFullTestsTestIdGet");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TestRead;
      return this.apiClient.callApi(
        '/full/tests/{test_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить тест
     * Возвращает тест по идентификатору.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestRead}
     */
    getTestFullTestsTestIdGet(testId) {
      return this.getTestFullTestsTestIdGetWithHttpInfo(testId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить материал темы
     * Возвращает метаданные материала темы с проверкой доступа.
     * @param {Number} contentId 
     * @param {Object} opts Optional parameters
     * @param {Number} [courseId] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicContentRead} and HTTP response
     */
    getTopicContentFullTopicContentsContentIdGetWithHttpInfo(contentId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling getTopicContentFullTopicContentsContentIdGet");
      }

      let pathParams = {
        'content_id': contentId
      };
      let queryParams = {
        'course_id': opts['courseId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TopicContentRead;
      return this.apiClient.callApi(
        '/full/topic-contents/{content_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить материал темы
     * Возвращает метаданные материала темы с проверкой доступа.
     * @param {Number} contentId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicContentRead}
     */
    getTopicContentFullTopicContentsContentIdGet(contentId, opts) {
      return this.getTopicContentFullTopicContentsContentIdGetWithHttpInfo(contentId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Перечислить материалы темы
     * Возвращает список материалов темы с проверкой доступа.
     * @param {Number} topicId 
     * @param {Object} opts Optional parameters
     * @param {Number} [courseId] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TopicContentRead>} and HTTP response
     */
    getTopicContentsFullTopicsTopicIdContentsGetWithHttpInfo(topicId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'topicId' is set
      if (topicId === undefined || topicId === null) {
        throw new Error("Missing the required parameter 'topicId' when calling getTopicContentsFullTopicsTopicIdContentsGet");
      }

      let pathParams = {
        'topic_id': topicId
      };
      let queryParams = {
        'course_id': opts['courseId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TopicContentRead];
      return this.apiClient.callApi(
        '/full/topics/{topic_id}/contents', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Перечислить материалы темы
     * Возвращает список материалов темы с проверкой доступа.
     * @param {Number} topicId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TopicContentRead>}
     */
    getTopicContentsFullTopicsTopicIdContentsGet(topicId, opts) {
      return this.getTopicContentsFullTopicsTopicIdContentsGetWithHttpInfo(topicId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить тему
     * Возвращает тему с проверкой доступа для студентов и авторов.
     * @param {Number} topicId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicRead} and HTTP response
     */
    getTopicFullTopicsTopicIdGetWithHttpInfo(topicId) {
      let postBody = null;
      // verify the required parameter 'topicId' is set
      if (topicId === undefined || topicId === null) {
        throw new Error("Missing the required parameter 'topicId' when calling getTopicFullTopicsTopicIdGet");
      }

      let pathParams = {
        'topic_id': topicId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TopicRead;
      return this.apiClient.callApi(
        '/full/topics/{topic_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить тему
     * Возвращает тему с проверкой доступа для студентов и авторов.
     * @param {Number} topicId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicRead}
     */
    getTopicFullTopicsTopicIdGet(topicId) {
      return this.getTopicFullTopicsTopicIdGetWithHttpInfo(topicId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Перечислить ответы вопроса
     * Возвращает все ответы конкретного вопроса.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AnswerRead>} and HTTP response
     */
    listAnswersFullQuestionsQuestionIdAnswersGetWithHttpInfo(questionId) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling listAnswersFullQuestionsQuestionIdAnswersGet");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [AnswerRead];
      return this.apiClient.callApi(
        '/full/questions/{question_id}/answers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Перечислить ответы вопроса
     * Возвращает все ответы конкретного вопроса.
     * @param {Number} questionId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AnswerRead>}
     */
    listAnswersFullQuestionsQuestionIdAnswersGet(questionId) {
      return this.listAnswersFullQuestionsQuestionIdAnswersGetWithHttpInfo(questionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить список курсов
     * Возвращает курсы с возможностью фильтрации по статусу публикации, автору и категории.
     * @param {Object} opts Optional parameters
     * @param {Boolean} [published] 
     * @param {Number} [authorId] 
     * @param {Number} [categoryId] 
     * @param {Number} [limit = 50)] 
     * @param {Number} [offset = 0)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CourseRead>} and HTTP response
     */
    listCoursesFullCoursesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'published': opts['published'],
        'authorId': opts['authorId'],
        'categoryId': opts['categoryId'],
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseRead];
      return this.apiClient.callApi(
        '/full/courses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить список курсов
     * Возвращает курсы с возможностью фильтрации по статусу публикации, автору и категории.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.published 
     * @param {Number} opts.authorId 
     * @param {Number} opts.categoryId 
     * @param {Number} opts.limit  (default to 50)
     * @param {Number} opts.offset  (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CourseRead>}
     */
    listCoursesFullCoursesGet(opts) {
      return this.listCoursesFullCoursesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Перечислить модули курса
     * Возвращает все модули указанного курса в порядке их идентификаторов.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ModuleRead>} and HTTP response
     */
    listModulesForCourseFullCoursesCourseIdModulesGetWithHttpInfo(courseId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling listModulesForCourseFullCoursesCourseIdModulesGet");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModuleRead];
      return this.apiClient.callApi(
        '/full/courses/{course_id}/modules', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Перечислить модули курса
     * Возвращает все модули указанного курса в порядке их идентификаторов.
     * @param {Number} courseId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ModuleRead>}
     */
    listModulesForCourseFullCoursesCourseIdModulesGet(courseId) {
      return this.listModulesForCourseFullCoursesCourseIdModulesGetWithHttpInfo(courseId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Перечислить вопросы теста
     * Возвращает все вопросы указанного теста.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/QuestionRead>} and HTTP response
     */
    listQuestionsFullTestsTestIdQuestionsGetWithHttpInfo(testId) {
      let postBody = null;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling listQuestionsFullTestsTestIdQuestionsGet");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [QuestionRead];
      return this.apiClient.callApi(
        '/full/tests/{test_id}/questions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Перечислить вопросы теста
     * Возвращает все вопросы указанного теста.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/QuestionRead>}
     */
    listQuestionsFullTestsTestIdQuestionsGet(testId) {
      return this.listQuestionsFullTestsTestIdQuestionsGetWithHttpInfo(testId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Результаты теста
     * Перечисляет результаты прохождения теста для администратора или автора курса.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TestResultRead>} and HTTP response
     */
    listResultsForTestFullTestsTestIdResultsGetWithHttpInfo(testId) {
      let postBody = null;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling listResultsForTestFullTestsTestIdResultsGet");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TestResultRead];
      return this.apiClient.callApi(
        '/full/tests/{test_id}/results', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Результаты теста
     * Перечисляет результаты прохождения теста для администратора или автора курса.
     * @param {Number} testId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TestResultRead>}
     */
    listResultsForTestFullTestsTestIdResultsGet(testId) {
      return this.listResultsForTestFullTestsTestIdResultsGetWithHttpInfo(testId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список тестов
     * Возвращает тесты с фильтрами по курсу и модулю.
     * @param {Object} opts Optional parameters
     * @param {Number} [courseId] 
     * @param {Number} [moduleId] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TestRead>} and HTTP response
     */
    listTestsFullTestsGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'course_id': opts['courseId'],
        'module_id': opts['moduleId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TestRead];
      return this.apiClient.callApi(
        '/full/tests', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список тестов
     * Возвращает тесты с фильтрами по курсу и модулю.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.courseId 
     * @param {Number} opts.moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TestRead>}
     */
    listTestsFullTestsGet(opts) {
      return this.listTestsFullTestsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список тем модуля
     * Возвращает темы модуля с проверкой доступа и прогресса студента.
     * @param {Number} courseId 
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TopicRead>} and HTTP response
     */
    listTopicsFullCoursesCourseIdModulesModuleIdTopicsGetWithHttpInfo(courseId, moduleId) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling listTopicsFullCoursesCourseIdModulesModuleIdTopicsGet");
      }
      // verify the required parameter 'moduleId' is set
      if (moduleId === undefined || moduleId === null) {
        throw new Error("Missing the required parameter 'moduleId' when calling listTopicsFullCoursesCourseIdModulesModuleIdTopicsGet");
      }

      let pathParams = {
        'course_id': courseId,
        'module_id': moduleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TopicRead];
      return this.apiClient.callApi(
        '/full/courses/{course_id}/modules/{module_id}/topics', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список тем модуля
     * Возвращает темы модуля с проверкой доступа и прогресса студента.
     * @param {Number} courseId 
     * @param {Number} moduleId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TopicRead>}
     */
    listTopicsFullCoursesCourseIdModulesModuleIdTopicsGet(courseId, moduleId) {
      return this.listTopicsFullCoursesCourseIdModulesModuleIdTopicsGetWithHttpInfo(courseId, moduleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Опубликовать или скрыть курс
     * Переключает флаг публикации курса. Доступно только автору курса.
     * @param {Number} courseId 
     * @param {Boolean} publish 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    publishCourseFullCoursesCourseIdPublishPatchWithHttpInfo(courseId, publish) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling publishCourseFullCoursesCourseIdPublishPatch");
      }
      // verify the required parameter 'publish' is set
      if (publish === undefined || publish === null) {
        throw new Error("Missing the required parameter 'publish' when calling publishCourseFullCoursesCourseIdPublishPatch");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
        'publish': publish
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/publish', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Опубликовать или скрыть курс
     * Переключает флаг публикации курса. Доступно только автору курса.
     * @param {Number} courseId 
     * @param {Boolean} publish 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    publishCourseFullCoursesCourseIdPublishPatch(courseId, publish) {
      return this.publishCourseFullCoursesCourseIdPublishPatchWithHttpInfo(courseId, publish)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Отдать картинку курса
     * Возвращает файл картинки курса по имени.
     * @param {String} filename 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    serveCoursePictureFullUploadsCoursesFilenameGetWithHttpInfo(filename) {
      let postBody = null;
      // verify the required parameter 'filename' is set
      if (filename === undefined || filename === null) {
        throw new Error("Missing the required parameter 'filename' when calling serveCoursePictureFullUploadsCoursesFilenameGet");
      }

      let pathParams = {
        'filename': filename
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/uploads/courses/{filename}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Отдать картинку курса
     * Возвращает файл картинки курса по имени.
     * @param {String} filename 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    serveCoursePictureFullUploadsCoursesFilenameGet(filename) {
      return this.serveCoursePictureFullUploadsCoursesFilenameGetWithHttpInfo(filename)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Отдать картинку вопроса по имени
     * Возвращает файл картинки вопроса по имени.
     * @param {String} filename 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    serveQuestionFileFullUploadsQuestionsFilenameGetWithHttpInfo(filename) {
      let postBody = null;
      // verify the required parameter 'filename' is set
      if (filename === undefined || filename === null) {
        throw new Error("Missing the required parameter 'filename' when calling serveQuestionFileFullUploadsQuestionsFilenameGet");
      }

      let pathParams = {
        'filename': filename
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/full/uploads/questions/{filename}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Отдать картинку вопроса по имени
     * Возвращает файл картинки вопроса по имени.
     * @param {String} filename 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    serveQuestionFileFullUploadsQuestionsFilenameGet(filename) {
      return this.serveQuestionFileFullUploadsQuestionsFilenameGetWithHttpInfo(filename)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить ответ
     * Изменяет текст и правильность ответа. Доступно только автору курса.
     * @param {Number} answerId 
     * @param {module:model/AnswerCreate} answerCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnswerRead} and HTTP response
     */
    updateAnswerFullAnswersAnswerIdPutWithHttpInfo(answerId, answerCreate) {
      let postBody = answerCreate;
      // verify the required parameter 'answerId' is set
      if (answerId === undefined || answerId === null) {
        throw new Error("Missing the required parameter 'answerId' when calling updateAnswerFullAnswersAnswerIdPut");
      }
      // verify the required parameter 'answerCreate' is set
      if (answerCreate === undefined || answerCreate === null) {
        throw new Error("Missing the required parameter 'answerCreate' when calling updateAnswerFullAnswersAnswerIdPut");
      }

      let pathParams = {
        'answer_id': answerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AnswerRead;
      return this.apiClient.callApi(
        '/full/answers/{answer_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить ответ
     * Изменяет текст и правильность ответа. Доступно только автору курса.
     * @param {Number} answerId 
     * @param {module:model/AnswerCreate} answerCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnswerRead}
     */
    updateAnswerFullAnswersAnswerIdPut(answerId, answerCreate) {
      return this.updateAnswerFullAnswersAnswerIdPutWithHttpInfo(answerId, answerCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить курс
     * Изменяет основные поля курса. Доступно только автору курса.
     * @param {Number} courseId 
     * @param {module:model/CourseCreate} courseCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseRead} and HTTP response
     */
    updateCourseFullCoursesCourseIdPutWithHttpInfo(courseId, courseCreate) {
      let postBody = courseCreate;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling updateCourseFullCoursesCourseIdPut");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CourseRead;
      return this.apiClient.callApi(
        '/full/courses/{course_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить курс
     * Изменяет основные поля курса. Доступно только автору курса.
     * @param {Number} courseId 
     * @param {module:model/CourseCreate} courseCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseRead}
     */
    updateCourseFullCoursesCourseIdPut(courseId, courseCreate) {
      return this.updateCourseFullCoursesCourseIdPutWithHttpInfo(courseId, courseCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить модуль
     * Изменяет название и описание модуля. Доступно только автору курса.
     * @param {Number} moduleId 
     * @param {module:model/ModuleCreate} moduleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ModuleRead} and HTTP response
     */
    updateModuleFullModulesModuleIdPutWithHttpInfo(moduleId, moduleCreate) {
      let postBody = moduleCreate;
      // verify the required parameter 'moduleId' is set
      if (moduleId === undefined || moduleId === null) {
        throw new Error("Missing the required parameter 'moduleId' when calling updateModuleFullModulesModuleIdPut");
      }
      // verify the required parameter 'moduleCreate' is set
      if (moduleCreate === undefined || moduleCreate === null) {
        throw new Error("Missing the required parameter 'moduleCreate' when calling updateModuleFullModulesModuleIdPut");
      }

      let pathParams = {
        'module_id': moduleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ModuleRead;
      return this.apiClient.callApi(
        '/full/modules/{module_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить модуль
     * Изменяет название и описание модуля. Доступно только автору курса.
     * @param {Number} moduleId 
     * @param {module:model/ModuleCreate} moduleCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ModuleRead}
     */
    updateModuleFullModulesModuleIdPut(moduleId, moduleCreate) {
      return this.updateModuleFullModulesModuleIdPutWithHttpInfo(moduleId, moduleCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить вопрос
     * Редактирует текст и сложность вопроса. Доступно только автору курса.
     * @param {Number} questionId 
     * @param {module:model/QuestionCreate} questionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/QuestionRead} and HTTP response
     */
    updateQuestionFullQuestionsQuestionIdPutWithHttpInfo(questionId, questionCreate) {
      let postBody = questionCreate;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling updateQuestionFullQuestionsQuestionIdPut");
      }
      // verify the required parameter 'questionCreate' is set
      if (questionCreate === undefined || questionCreate === null) {
        throw new Error("Missing the required parameter 'questionCreate' when calling updateQuestionFullQuestionsQuestionIdPut");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = QuestionRead;
      return this.apiClient.callApi(
        '/full/questions/{question_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить вопрос
     * Редактирует текст и сложность вопроса. Доступно только автору курса.
     * @param {Number} questionId 
     * @param {module:model/QuestionCreate} questionCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/QuestionRead}
     */
    updateQuestionFullQuestionsQuestionIdPut(questionId, questionCreate) {
      return this.updateQuestionFullQuestionsQuestionIdPutWithHttpInfo(questionId, questionCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить тест
     * Редактирует параметры теста и проверяет сохраняемую привязку к курсу или модулю.
     * @param {Number} testId 
     * @param {module:model/TestCreate} testCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TestRead} and HTTP response
     */
    updateTestFullTestsTestIdPutWithHttpInfo(testId, testCreate) {
      let postBody = testCreate;
      // verify the required parameter 'testId' is set
      if (testId === undefined || testId === null) {
        throw new Error("Missing the required parameter 'testId' when calling updateTestFullTestsTestIdPut");
      }
      // verify the required parameter 'testCreate' is set
      if (testCreate === undefined || testCreate === null) {
        throw new Error("Missing the required parameter 'testCreate' when calling updateTestFullTestsTestIdPut");
      }

      let pathParams = {
        'test_id': testId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TestRead;
      return this.apiClient.callApi(
        '/full/tests/{test_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить тест
     * Редактирует параметры теста и проверяет сохраняемую привязку к курсу или модулю.
     * @param {Number} testId 
     * @param {module:model/TestCreate} testCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TestRead}
     */
    updateTestFullTestsTestIdPut(testId, testCreate) {
      return this.updateTestFullTestsTestIdPutWithHttpInfo(testId, testCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить материал темы
     * Изменяет описание материала темы. Доступно только автору курса.
     * @param {Number} contentId 
     * @param {module:model/TopicContentCreate} topicContentCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicContentRead} and HTTP response
     */
    updateTopicContentFullTopicContentsContentIdPutWithHttpInfo(contentId, topicContentCreate) {
      let postBody = topicContentCreate;
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling updateTopicContentFullTopicContentsContentIdPut");
      }
      // verify the required parameter 'topicContentCreate' is set
      if (topicContentCreate === undefined || topicContentCreate === null) {
        throw new Error("Missing the required parameter 'topicContentCreate' when calling updateTopicContentFullTopicContentsContentIdPut");
      }

      let pathParams = {
        'content_id': contentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TopicContentRead;
      return this.apiClient.callApi(
        '/full/topic-contents/{content_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить материал темы
     * Изменяет описание материала темы. Доступно только автору курса.
     * @param {Number} contentId 
     * @param {module:model/TopicContentCreate} topicContentCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicContentRead}
     */
    updateTopicContentFullTopicContentsContentIdPut(contentId, topicContentCreate) {
      return this.updateTopicContentFullTopicContentsContentIdPutWithHttpInfo(contentId, topicContentCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить тему
     * Редактирует название и описание темы. Доступно только автору курса.
     * @param {Number} topicId 
     * @param {module:model/TopicCreate} topicCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TopicRead} and HTTP response
     */
    updateTopicFullTopicsTopicIdPutWithHttpInfo(topicId, topicCreate) {
      let postBody = topicCreate;
      // verify the required parameter 'topicId' is set
      if (topicId === undefined || topicId === null) {
        throw new Error("Missing the required parameter 'topicId' when calling updateTopicFullTopicsTopicIdPut");
      }
      // verify the required parameter 'topicCreate' is set
      if (topicCreate === undefined || topicCreate === null) {
        throw new Error("Missing the required parameter 'topicCreate' when calling updateTopicFullTopicsTopicIdPut");
      }

      let pathParams = {
        'topic_id': topicId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TopicRead;
      return this.apiClient.callApi(
        '/full/topics/{topic_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить тему
     * Редактирует название и описание темы. Доступно только автору курса.
     * @param {Number} topicId 
     * @param {module:model/TopicCreate} topicCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TopicRead}
     */
    updateTopicFullTopicsTopicIdPut(topicId, topicCreate) {
      return this.updateTopicFullTopicsTopicIdPutWithHttpInfo(topicId, topicCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Загрузить картинку курса
     * Загружает изображение для курса (только автор курса).
     * @param {Number} courseId 
     * @param {File} file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CourseRead} and HTTP response
     */
    uploadCoursePictureFullCoursesCourseIdPicturePostWithHttpInfo(courseId, file) {
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling uploadCoursePictureFullCoursesCourseIdPicturePost");
      }
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling uploadCoursePictureFullCoursesCourseIdPicturePost");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = CourseRead;
      return this.apiClient.callApi(
        '/full/courses/{course_id}/picture', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Загрузить картинку курса
     * Загружает изображение для курса (только автор курса).
     * @param {Number} courseId 
     * @param {File} file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CourseRead}
     */
    uploadCoursePictureFullCoursesCourseIdPicturePost(courseId, file) {
      return this.uploadCoursePictureFullCoursesCourseIdPicturePostWithHttpInfo(courseId, file)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Загрузить картинку для вопроса
     * Загружает файл изображения для вопроса (author или admin).
     * @param {Number} questionId 
     * @param {File} file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/QuestionRead} and HTTP response
     */
    uploadQuestionPictureFullQuestionsQuestionIdPicturePostWithHttpInfo(questionId, file) {
      let postBody = null;
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling uploadQuestionPictureFullQuestionsQuestionIdPicturePost");
      }
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling uploadQuestionPictureFullQuestionsQuestionIdPicturePost");
      }

      let pathParams = {
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = QuestionRead;
      return this.apiClient.callApi(
        '/full/questions/{question_id}/picture', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Загрузить картинку для вопроса
     * Загружает файл изображения для вопроса (author или admin).
     * @param {Number} questionId 
     * @param {File} file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/QuestionRead}
     */
    uploadQuestionPictureFullQuestionsQuestionIdPicturePost(questionId, file) {
      return this.uploadQuestionPictureFullQuestionsQuestionIdPicturePostWithHttpInfo(questionId, file)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
