/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CourseRead from '../model/CourseRead';
import LoginIn from '../model/LoginIn';
import RoleUpdate from '../model/RoleUpdate';
import TokenOut from '../model/TokenOut';
import UserCreate from '../model/UserCreate';
import UserRead from '../model/UserRead';

/**
* Users service.
* @module api/UsersApi
* @version 0.1.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the loginFormUsersLoginFormPost operation.
     * @callback module:api/UsersApi~loginFormUsersLoginFormPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenOut} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Войти через form-data
     * Совместимый с OAuth2 endpoint, принимает данные формы и возвращает JWT токен.
     * @param {String} username 
     * @param {String} password 
     * @param {Object} opts Optional parameters
     * @param {String} [grantType] 
     * @param {String} [scope = '')] 
     * @param {String} [clientId] 
     * @param {String} [clientSecret] 
     * @param {module:api/UsersApi~loginFormUsersLoginFormPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenOut}
     */
    loginFormUsersLoginFormPost(username, password, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling loginFormUsersLoginFormPost");
      }
      // verify the required parameter 'password' is set
      if (password === undefined || password === null) {
        throw new Error("Missing the required parameter 'password' when calling loginFormUsersLoginFormPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'grant_type': opts['grantType'],
        'username': username,
        'password': password,
        'scope': opts['scope'],
        'client_id': opts['clientId'],
        'client_secret': opts['clientSecret']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = TokenOut;
      return this.apiClient.callApi(
        '/users/login-form', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loginUsersLoginPost operation.
     * @callback module:api/UsersApi~loginUsersLoginPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenOut} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Войти по JSON-параметрам
     * Аутентифицирует пользователя по логину и паролю, возвращает JWT токен.
     * @param {module:model/LoginIn} loginIn 
     * @param {module:api/UsersApi~loginUsersLoginPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TokenOut}
     */
    loginUsersLoginPost(loginIn, callback) {
      let postBody = loginIn;
      // verify the required parameter 'loginIn' is set
      if (loginIn === undefined || loginIn === null) {
        throw new Error("Missing the required parameter 'loginIn' when calling loginUsersLoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TokenOut;
      return this.apiClient.callApi(
        '/users/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the logoutUsersLogoutPost operation.
     * @callback module:api/UsersApi~logoutUsersLogoutPostCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Завершить сессию
     * Возвращает успешный ответ; фактическое удаление токена выполняется на клиенте.
     * @param {module:api/UsersApi~logoutUsersLogoutPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    logoutUsersLogoutPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/users/logout', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the meUsersMeGet operation.
     * @callback module:api/UsersApi~meUsersMeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRead} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получить профиль текущего пользователя
     * Возвращает информацию о текущем аутентифицированном пользователе.
     * @param {module:api/UsersApi~meUsersMeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRead}
     */
    meUsersMeGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserRead;
      return this.apiClient.callApi(
        '/users/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the myEnrolledCoursesUsersMeCoursesEnrolledGet operation.
     * @callback module:api/UsersApi~myEnrolledCoursesUsersMeCoursesEnrolledGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CourseRead>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список курсов, на которые пользователь записан
     * Возвращает опубликованные курсы, в которых текущий пользователь участвует как студент.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 20)] 
     * @param {Number} [offset = 0)] 
     * @param {module:api/UsersApi~myEnrolledCoursesUsersMeCoursesEnrolledGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CourseRead>}
     */
    myEnrolledCoursesUsersMeCoursesEnrolledGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseRead];
      return this.apiClient.callApi(
        '/users/me/courses/enrolled', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the myTeachingCoursesUsersMeCoursesTeachingGet operation.
     * @callback module:api/UsersApi~myTeachingCoursesUsersMeCoursesTeachingGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CourseRead>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список курсов, которые ведет пользователь
     * Возвращает авторские курсы текущего пользователя.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 20)] 
     * @param {Number} [offset = 0)] 
     * @param {module:api/UsersApi~myTeachingCoursesUsersMeCoursesTeachingGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CourseRead>}
     */
    myTeachingCoursesUsersMeCoursesTeachingGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseRead];
      return this.apiClient.callApi(
        '/users/me/courses/teaching', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the registerUsersRegisterPost operation.
     * @callback module:api/UsersApi~registerUsersRegisterPostCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Зарегистрировать нового пользователя
     * Создает учетную запись студента с уникальным логином и хешированным паролем.
     * @param {module:model/UserCreate} userCreate 
     * @param {module:api/UsersApi~registerUsersRegisterPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    registerUsersRegisterPost(userCreate, callback) {
      let postBody = userCreate;
      // verify the required parameter 'userCreate' is set
      if (userCreate === undefined || userCreate === null) {
        throw new Error("Missing the required parameter 'userCreate' when calling registerUsersRegisterPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/users/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUserRoleUsersUserIdRolePut operation.
     * @callback module:api/UsersApi~updateUserRoleUsersUserIdRolePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserRead} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Изменить роль пользователя
     * Позволяет администратору обновить роль существующего пользователя.
     * @param {Number} userId 
     * @param {module:model/RoleUpdate} roleUpdate 
     * @param {module:api/UsersApi~updateUserRoleUsersUserIdRolePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserRead}
     */
    updateUserRoleUsersUserIdRolePut(userId, roleUpdate, callback) {
      let postBody = roleUpdate;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateUserRoleUsersUserIdRolePut");
      }
      // verify the required parameter 'roleUpdate' is set
      if (roleUpdate === undefined || roleUpdate === null) {
        throw new Error("Missing the required parameter 'roleUpdate' when calling updateUserRoleUsersUserIdRolePut");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserRead;
      return this.apiClient.callApi(
        '/users/{user_id}/role', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
