/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CourseEnrollmentRead from '../model/CourseEnrollmentRead';
import CourseRead from '../model/CourseRead';
import LoginIn from '../model/LoginIn';
import RoleUpdate from '../model/RoleUpdate';
import TokenOut from '../model/TokenOut';
import UserCreate from '../model/UserCreate';
import UserRead from '../model/UserRead';

/**
* Users service.
* @module api/UsersApi
* @version 0.1.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Войти через form-data
     * Совместимый с OAuth2 endpoint, принимает данные формы и возвращает JWT токен.
     * @param {String} username 
     * @param {String} password 
     * @param {Object} opts Optional parameters
     * @param {String} [grantType] 
     * @param {String} [scope = '')] 
     * @param {String} [clientId] 
     * @param {String} [clientSecret] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TokenOut} and HTTP response
     */
    loginFormUsersLoginFormPostWithHttpInfo(username, password, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling loginFormUsersLoginFormPost");
      }
      // verify the required parameter 'password' is set
      if (password === undefined || password === null) {
        throw new Error("Missing the required parameter 'password' when calling loginFormUsersLoginFormPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'grant_type': opts['grantType'],
        'username': username,
        'password': password,
        'scope': opts['scope'],
        'client_id': opts['clientId'],
        'client_secret': opts['clientSecret']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = TokenOut;
      return this.apiClient.callApi(
        '/users/login-form', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Войти через form-data
     * Совместимый с OAuth2 endpoint, принимает данные формы и возвращает JWT токен.
     * @param {String} username 
     * @param {String} password 
     * @param {Object} opts Optional parameters
     * @param {String} opts.grantType 
     * @param {String} opts.scope  (default to '')
     * @param {String} opts.clientId 
     * @param {String} opts.clientSecret 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TokenOut}
     */
    loginFormUsersLoginFormPost(username, password, opts) {
      return this.loginFormUsersLoginFormPostWithHttpInfo(username, password, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Войти по JSON-параметрам
     * Аутентифицирует пользователя по логину и паролю, возвращает JWT токен.
     * @param {module:model/LoginIn} loginIn 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TokenOut} and HTTP response
     */
    loginUsersLoginPostWithHttpInfo(loginIn) {
      let postBody = loginIn;
      // verify the required parameter 'loginIn' is set
      if (loginIn === undefined || loginIn === null) {
        throw new Error("Missing the required parameter 'loginIn' when calling loginUsersLoginPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TokenOut;
      return this.apiClient.callApi(
        '/users/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Войти по JSON-параметрам
     * Аутентифицирует пользователя по логину и паролю, возвращает JWT токен.
     * @param {module:model/LoginIn} loginIn 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TokenOut}
     */
    loginUsersLoginPost(loginIn) {
      return this.loginUsersLoginPostWithHttpInfo(loginIn)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Завершить сессию
     * Возвращает успешный ответ; фактическое удаление токена выполняется на клиенте.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    logoutUsersLogoutPostWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/users/logout', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Завершить сессию
     * Возвращает успешный ответ; фактическое удаление токена выполняется на клиенте.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    logoutUsersLogoutPost() {
      return this.logoutUsersLogoutPostWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить профиль текущего пользователя
     * Возвращает информацию о текущем аутентифицированном пользователе.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserRead} and HTTP response
     */
    meUsersMeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserRead;
      return this.apiClient.callApi(
        '/users/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить профиль текущего пользователя
     * Возвращает информацию о текущем аутентифицированном пользователе.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserRead}
     */
    meUsersMeGet() {
      return this.meUsersMeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список курсов, на которые пользователь записан
     * Возвращает опубликованные курсы, в которых текущий пользователь участвует как студент.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 20)] 
     * @param {Number} [offset = 0)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CourseRead>} and HTTP response
     */
    myEnrolledCoursesUsersMeCoursesEnrolledGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseRead];
      return this.apiClient.callApi(
        '/users/me/courses/enrolled', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список курсов, на которые пользователь записан
     * Возвращает опубликованные курсы, в которых текущий пользователь участвует как студент.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit  (default to 20)
     * @param {Number} opts.offset  (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CourseRead>}
     */
    myEnrolledCoursesUsersMeCoursesEnrolledGet(opts) {
      return this.myEnrolledCoursesUsersMeCoursesEnrolledGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список записей на курсы текущего пользователя
     * Возвращает список CourseEnrollment для текущего пользователя (даты начала/окончания).
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CourseEnrollmentRead>} and HTTP response
     */
    myEnrollmentsUsersMeEnrollmentsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseEnrollmentRead];
      return this.apiClient.callApi(
        '/users/me/enrollments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список записей на курсы текущего пользователя
     * Возвращает список CourseEnrollment для текущего пользователя (даты начала/окончания).
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CourseEnrollmentRead>}
     */
    myEnrollmentsUsersMeEnrollmentsGet() {
      return this.myEnrollmentsUsersMeEnrollmentsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Список курсов, которые ведет пользователь
     * Возвращает авторские курсы текущего пользователя.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 20)] 
     * @param {Number} [offset = 0)] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CourseRead>} and HTTP response
     */
    myTeachingCoursesUsersMeCoursesTeachingGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CourseRead];
      return this.apiClient.callApi(
        '/users/me/courses/teaching', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Список курсов, которые ведет пользователь
     * Возвращает авторские курсы текущего пользователя.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit  (default to 20)
     * @param {Number} opts.offset  (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CourseRead>}
     */
    myTeachingCoursesUsersMeCoursesTeachingGet(opts) {
      return this.myTeachingCoursesUsersMeCoursesTeachingGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Зарегистрировать нового пользователя
     * Создает учетную запись студента с уникальным логином и хешированным паролем.
     * @param {module:model/UserCreate} userCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    registerUsersRegisterPostWithHttpInfo(userCreate) {
      let postBody = userCreate;
      // verify the required parameter 'userCreate' is set
      if (userCreate === undefined || userCreate === null) {
        throw new Error("Missing the required parameter 'userCreate' when calling registerUsersRegisterPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/users/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Зарегистрировать нового пользователя
     * Создает учетную запись студента с уникальным логином и хешированным паролем.
     * @param {module:model/UserCreate} userCreate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    registerUsersRegisterPost(userCreate) {
      return this.registerUsersRegisterPostWithHttpInfo(userCreate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Изменить роль пользователя
     * Позволяет администратору обновить роль существующего пользователя.
     * @param {Number} userId 
     * @param {module:model/RoleUpdate} roleUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserRead} and HTTP response
     */
    updateUserRoleUsersUserIdRolePutWithHttpInfo(userId, roleUpdate) {
      let postBody = roleUpdate;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateUserRoleUsersUserIdRolePut");
      }
      // verify the required parameter 'roleUpdate' is set
      if (roleUpdate === undefined || roleUpdate === null) {
        throw new Error("Missing the required parameter 'roleUpdate' when calling updateUserRoleUsersUserIdRolePut");
      }

      let pathParams = {
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserRead;
      return this.apiClient.callApi(
        '/users/{user_id}/role', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Изменить роль пользователя
     * Позволяет администратору обновить роль существующего пользователя.
     * @param {Number} userId 
     * @param {module:model/RoleUpdate} roleUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserRead}
     */
    updateUserRoleUsersUserIdRolePut(userId, roleUpdate) {
      return this.updateUserRoleUsersUserIdRolePutWithHttpInfo(userId, roleUpdate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
