/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AnswerCreate from './model/AnswerCreate';
import AnswerRead from './model/AnswerRead';
import CourseCategoryCreate from './model/CourseCategoryCreate';
import CourseCategoryRead from './model/CourseCategoryRead';
import CourseCreate from './model/CourseCreate';
import CourseEnrollmentRead from './model/CourseEnrollmentRead';
import CourseRead from './model/CourseRead';
import LoginIn from './model/LoginIn';
import ModuleCreate from './model/ModuleCreate';
import ModuleRead from './model/ModuleRead';
import PermissionCreate from './model/PermissionCreate';
import PermissionRead from './model/PermissionRead';
import QuestionCreate from './model/QuestionCreate';
import QuestionRead from './model/QuestionRead';
import RoleCreate from './model/RoleCreate';
import RolePermissionCreate from './model/RolePermissionCreate';
import RolePermissionRead from './model/RolePermissionRead';
import RoleRead from './model/RoleRead';
import RoleUpdate from './model/RoleUpdate';
import TestCreate from './model/TestCreate';
import TestRead from './model/TestRead';
import TestResultRead from './model/TestResultRead';
import TokenOut from './model/TokenOut';
import TopicContentCreate from './model/TopicContentCreate';
import TopicContentRead from './model/TopicContentRead';
import TopicCreate from './model/TopicCreate';
import TopicRead from './model/TopicRead';
import UserCreate from './model/UserCreate';
import UserRead from './model/UserRead';
import DefaultApi from './api/DefaultApi';
import FullApi from './api/FullApi';
import TeachingApi from './api/TeachingApi';
import UsersApi from './api/UsersApi';

export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnswerCreate model constructor.
     * @property {module:model/AnswerCreate}
     */
    AnswerCreate,

    /**
     * The AnswerRead model constructor.
     * @property {module:model/AnswerRead}
     */
    AnswerRead,

    /**
     * The CourseCategoryCreate model constructor.
     * @property {module:model/CourseCategoryCreate}
     */
    CourseCategoryCreate,

    /**
     * The CourseCategoryRead model constructor.
     * @property {module:model/CourseCategoryRead}
     */
    CourseCategoryRead,

    /**
     * The CourseCreate model constructor.
     * @property {module:model/CourseCreate}
     */
    CourseCreate,

    /**
     * The CourseEnrollmentRead model constructor.
     * @property {module:model/CourseEnrollmentRead}
     */
    CourseEnrollmentRead,

    /**
     * The CourseRead model constructor.
     * @property {module:model/CourseRead}
     */
    CourseRead,


    /**
     * The LoginIn model constructor.
     * @property {module:model/LoginIn}
     */
    LoginIn,

    /**
     * The ModuleCreate model constructor.
     * @property {module:model/ModuleCreate}
     */
    ModuleCreate,

    /**
     * The ModuleRead model constructor.
     * @property {module:model/ModuleRead}
     */
    ModuleRead,

    /**
     * The PermissionCreate model constructor.
     * @property {module:model/PermissionCreate}
     */
    PermissionCreate,

    /**
     * The PermissionRead model constructor.
     * @property {module:model/PermissionRead}
     */
    PermissionRead,

    /**
     * The QuestionCreate model constructor.
     * @property {module:model/QuestionCreate}
     */
    QuestionCreate,

    /**
     * The QuestionRead model constructor.
     * @property {module:model/QuestionRead}
     */
    QuestionRead,

    /**
     * The RoleCreate model constructor.
     * @property {module:model/RoleCreate}
     */
    RoleCreate,

    /**
     * The RolePermissionCreate model constructor.
     * @property {module:model/RolePermissionCreate}
     */
    RolePermissionCreate,

    /**
     * The RolePermissionRead model constructor.
     * @property {module:model/RolePermissionRead}
     */
    RolePermissionRead,

    /**
     * The RoleRead model constructor.
     * @property {module:model/RoleRead}
     */
    RoleRead,

    /**
     * The RoleUpdate model constructor.
     * @property {module:model/RoleUpdate}
     */
    RoleUpdate,

    /**
     * The TestCreate model constructor.
     * @property {module:model/TestCreate}
     */
    TestCreate,

    /**
     * The TestRead model constructor.
     * @property {module:model/TestRead}
     */
    TestRead,

    /**
     * The TestResultRead model constructor.
     * @property {module:model/TestResultRead}
     */
    TestResultRead,

    /**
     * The TokenOut model constructor.
     * @property {module:model/TokenOut}
     */
    TokenOut,

    /**
     * The TopicContentCreate model constructor.
     * @property {module:model/TopicContentCreate}
     */
    TopicContentCreate,

    /**
     * The TopicContentRead model constructor.
     * @property {module:model/TopicContentRead}
     */
    TopicContentRead,

    /**
     * The TopicCreate model constructor.
     * @property {module:model/TopicCreate}
     */
    TopicCreate,

    /**
     * The TopicRead model constructor.
     * @property {module:model/TopicRead}
     */
    TopicRead,

    /**
     * The UserCreate model constructor.
     * @property {module:model/UserCreate}
     */
    UserCreate,

    /**
     * The UserRead model constructor.
     * @property {module:model/UserRead}
     */
    UserRead,


    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The FullApi service constructor.
    * @property {module:api/FullApi}
    */
    FullApi,

    /**
    * The TeachingApi service constructor.
    * @property {module:api/TeachingApi}
    */
    TeachingApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
