/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnswerCreate model module.
 * @module model/AnswerCreate
 * @version 0.1.0
 */
class AnswerCreate {
    /**
     * Constructs a new <code>AnswerCreate</code>.
     * @alias module:model/AnswerCreate
     * @param isCorrect {Boolean} 
     * @param text {String} 
     * @param questionId {Number} 
     */
    constructor(isCorrect, text, questionId) { 
        
        AnswerCreate.initialize(this, isCorrect, text, questionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isCorrect, text, questionId) { 
        obj['isCorrect'] = isCorrect;
        obj['text'] = text;
        obj['questionId'] = questionId;
    }

    /**
     * Constructs a <code>AnswerCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnswerCreate} obj Optional instance to populate.
     * @return {module:model/AnswerCreate} The populated <code>AnswerCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnswerCreate();

            if (data.hasOwnProperty('isCorrect')) {
                obj['isCorrect'] = ApiClient.convertToType(data['isCorrect'], 'Boolean');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('questionId')) {
                obj['questionId'] = ApiClient.convertToType(data['questionId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnswerCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnswerCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AnswerCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}

AnswerCreate.RequiredProperties = ["isCorrect", "text", "questionId"];

/**
 * @member {Boolean} isCorrect
 */
AnswerCreate.prototype['isCorrect'] = undefined;

/**
 * @member {String} text
 */
AnswerCreate.prototype['text'] = undefined;

/**
 * @member {Number} questionId
 */
AnswerCreate.prototype['questionId'] = undefined;






export default AnswerCreate;

