/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CourseCreate model module.
 * @module model/CourseCreate
 * @version 0.1.0
 */
class CourseCreate {
    /**
     * Constructs a new <code>CourseCreate</code>.
     * @alias module:model/CourseCreate
     * @param name {String} 
     * @param description {String} 
     * @param categoryId {Number} 
     * @param authorId {Number} 
     */
    constructor(name, description, categoryId, authorId) { 
        
        CourseCreate.initialize(this, name, description, categoryId, authorId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, categoryId, authorId) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['categoryId'] = categoryId;
        obj['authorId'] = authorId;
    }

    /**
     * Constructs a <code>CourseCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CourseCreate} obj Optional instance to populate.
     * @return {module:model/CourseCreate} The populated <code>CourseCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CourseCreate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'Number');
            }
            if (data.hasOwnProperty('authorId')) {
                obj['authorId'] = ApiClient.convertToType(data['authorId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CourseCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CourseCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CourseCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

CourseCreate.RequiredProperties = ["name", "description", "categoryId", "authorId"];

/**
 * @member {String} name
 */
CourseCreate.prototype['name'] = undefined;

/**
 * @member {String} description
 */
CourseCreate.prototype['description'] = undefined;

/**
 * @member {Number} categoryId
 */
CourseCreate.prototype['categoryId'] = undefined;

/**
 * @member {Number} authorId
 */
CourseCreate.prototype['authorId'] = undefined;






export default CourseCreate;

