/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CourseEnrollmentRead model module.
 * @module model/CourseEnrollmentRead
 * @version 0.1.0
 */
class CourseEnrollmentRead {
    /**
     * Constructs a new <code>CourseEnrollmentRead</code>.
     * @alias module:model/CourseEnrollmentRead
     * @param id {Number} 
     * @param dateStarted {String} 
     * @param dateEnded {String} 
     * @param courseId {Number} 
     * @param userId {Number} 
     */
    constructor(id, dateStarted, dateEnded, courseId, userId) { 
        
        CourseEnrollmentRead.initialize(this, id, dateStarted, dateEnded, courseId, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, dateStarted, dateEnded, courseId, userId) { 
        obj['id'] = id;
        obj['dateStarted'] = dateStarted;
        obj['dateEnded'] = dateEnded;
        obj['courseId'] = courseId;
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>CourseEnrollmentRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CourseEnrollmentRead} obj Optional instance to populate.
     * @return {module:model/CourseEnrollmentRead} The populated <code>CourseEnrollmentRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CourseEnrollmentRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('dateStarted')) {
                obj['dateStarted'] = ApiClient.convertToType(data['dateStarted'], 'String');
            }
            if (data.hasOwnProperty('dateEnded')) {
                obj['dateEnded'] = ApiClient.convertToType(data['dateEnded'], 'String');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CourseEnrollmentRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CourseEnrollmentRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CourseEnrollmentRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dateStarted'] && !(typeof data['dateStarted'] === 'string' || data['dateStarted'] instanceof String)) {
            throw new Error("Expected the field `dateStarted` to be a primitive type in the JSON string but got " + data['dateStarted']);
        }
        // ensure the json data is a string
        if (data['dateEnded'] && !(typeof data['dateEnded'] === 'string' || data['dateEnded'] instanceof String)) {
            throw new Error("Expected the field `dateEnded` to be a primitive type in the JSON string but got " + data['dateEnded']);
        }

        return true;
    }


}

CourseEnrollmentRead.RequiredProperties = ["id", "dateStarted", "dateEnded", "courseId", "userId"];

/**
 * @member {Number} id
 */
CourseEnrollmentRead.prototype['id'] = undefined;

/**
 * @member {String} dateStarted
 */
CourseEnrollmentRead.prototype['dateStarted'] = undefined;

/**
 * @member {String} dateEnded
 */
CourseEnrollmentRead.prototype['dateEnded'] = undefined;

/**
 * @member {Number} courseId
 */
CourseEnrollmentRead.prototype['courseId'] = undefined;

/**
 * @member {Number} userId
 */
CourseEnrollmentRead.prototype['userId'] = undefined;






export default CourseEnrollmentRead;

