/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginIn model module.
 * @module model/LoginIn
 * @version 0.1.0
 */
class LoginIn {
    /**
     * Constructs a new <code>LoginIn</code>.
     * @alias module:model/LoginIn
     * @param login {String} 
     * @param password {String} 
     */
    constructor(login, password) { 
        
        LoginIn.initialize(this, login, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, login, password) { 
        obj['login'] = login;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginIn} obj Optional instance to populate.
     * @return {module:model/LoginIn} The populated <code>LoginIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginIn();

            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginIn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginIn</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoginIn.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['login'] && !(typeof data['login'] === 'string' || data['login'] instanceof String)) {
            throw new Error("Expected the field `login` to be a primitive type in the JSON string but got " + data['login']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getLogin() {
        return this.login;
    }

    /**
     * @param {String} login
     */
    setLogin(login) {
        this['login'] = login;
    }
/**
     * @return {String}
     */
    getPassword() {
        return this.password;
    }

    /**
     * @param {String} password
     */
    setPassword(password) {
        this['password'] = password;
    }

}

LoginIn.RequiredProperties = ["login", "password"];

/**
 * @member {String} login
 */
LoginIn.prototype['login'] = undefined;

/**
 * @member {String} password
 */
LoginIn.prototype['password'] = undefined;






export default LoginIn;

