/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModuleRead model module.
 * @module model/ModuleRead
 * @version 0.1.0
 */
class ModuleRead {
    /**
     * Constructs a new <code>ModuleRead</code>.
     * @alias module:model/ModuleRead
     * @param id {Number} 
     * @param name {String} 
     * @param description {String} 
     * @param courseId {Number} 
     */
    constructor(id, name, description, courseId) { 
        
        ModuleRead.initialize(this, id, name, description, courseId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, description, courseId) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['description'] = description;
        obj['courseId'] = courseId;
    }

    /**
     * Constructs a <code>ModuleRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModuleRead} obj Optional instance to populate.
     * @return {module:model/ModuleRead} The populated <code>ModuleRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModuleRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModuleRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModuleRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ModuleRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ModuleRead.RequiredProperties = ["id", "name", "description", "courseId"];

/**
 * @member {Number} id
 */
ModuleRead.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ModuleRead.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ModuleRead.prototype['description'] = undefined;

/**
 * @member {Number} courseId
 */
ModuleRead.prototype['courseId'] = undefined;






export default ModuleRead;

