/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuestionRead model module.
 * @module model/QuestionRead
 * @version 0.1.0
 */
class QuestionRead {
    /**
     * Constructs a new <code>QuestionRead</code>.
     * @alias module:model/QuestionRead
     * @param id {Number} 
     * @param text {String} 
     * @param picture {String} 
     * @param complexityPoints {Number} 
     * @param testId {Number} 
     */
    constructor(id, text, picture, complexityPoints, testId) { 
        
        QuestionRead.initialize(this, id, text, picture, complexityPoints, testId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, text, picture, complexityPoints, testId) { 
        obj['id'] = id;
        obj['text'] = text;
        obj['picture'] = picture;
        obj['complexityPoints'] = complexityPoints;
        obj['testId'] = testId;
    }

    /**
     * Constructs a <code>QuestionRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuestionRead} obj Optional instance to populate.
     * @return {module:model/QuestionRead} The populated <code>QuestionRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuestionRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
            }
            if (data.hasOwnProperty('complexityPoints')) {
                obj['complexityPoints'] = ApiClient.convertToType(data['complexityPoints'], 'Number');
            }
            if (data.hasOwnProperty('testId')) {
                obj['testId'] = ApiClient.convertToType(data['testId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuestionRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuestionRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuestionRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['picture'] && !(typeof data['picture'] === 'string' || data['picture'] instanceof String)) {
            throw new Error("Expected the field `picture` to be a primitive type in the JSON string but got " + data['picture']);
        }

        return true;
    }


}

QuestionRead.RequiredProperties = ["id", "text", "picture", "complexityPoints", "testId"];

/**
 * @member {Number} id
 */
QuestionRead.prototype['id'] = undefined;

/**
 * @member {String} text
 */
QuestionRead.prototype['text'] = undefined;

/**
 * @member {String} picture
 */
QuestionRead.prototype['picture'] = undefined;

/**
 * @member {Number} complexityPoints
 */
QuestionRead.prototype['complexityPoints'] = undefined;

/**
 * @member {Number} testId
 */
QuestionRead.prototype['testId'] = undefined;






export default QuestionRead;

