/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuestionCreate model module.
 * @module model/QuestionCreate
 * @version 0.1.0
 */
class QuestionCreate {
    /**
     * Constructs a new <code>QuestionCreate</code>.
     * @alias module:model/QuestionCreate
     * @param text {String} 
     * @param complexityPoints {Number} 
     * @param testId {Number} 
     */
    constructor(text, complexityPoints, testId) { 
        
        QuestionCreate.initialize(this, text, complexityPoints, testId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text, complexityPoints, testId) { 
        obj['text'] = text;
        obj['complexityPoints'] = complexityPoints;
        obj['testId'] = testId;
    }

    /**
     * Constructs a <code>QuestionCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuestionCreate} obj Optional instance to populate.
     * @return {module:model/QuestionCreate} The populated <code>QuestionCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuestionCreate();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('complexityPoints')) {
                obj['complexityPoints'] = ApiClient.convertToType(data['complexityPoints'], 'Number');
            }
            if (data.hasOwnProperty('testId')) {
                obj['testId'] = ApiClient.convertToType(data['testId'], 'Number');
            }
            if (data.hasOwnProperty('questionType')) {
                obj['questionType'] = ApiClient.convertToType(data['questionType'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
            }
            if (data.hasOwnProperty('topicId')) {
                obj['topicId'] = ApiClient.convertToType(data['topicId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuestionCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuestionCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuestionCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['questionType'] && !(typeof data['questionType'] === 'string' || data['questionType'] instanceof String)) {
            throw new Error("Expected the field `questionType` to be a primitive type in the JSON string but got " + data['questionType']);
        }
        // ensure the json data is a string
        if (data['picture'] && !(typeof data['picture'] === 'string' || data['picture'] instanceof String)) {
            throw new Error("Expected the field `picture` to be a primitive type in the JSON string but got " + data['picture']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getText() {
        return this.text;
    }

    /**
     * @param {String} text
     */
    setText(text) {
        this['text'] = text;
    }
/**
     * @return {Number}
     */
    getComplexityPoints() {
        return this.complexityPoints;
    }

    /**
     * @param {Number} complexityPoints
     */
    setComplexityPoints(complexityPoints) {
        this['complexityPoints'] = complexityPoints;
    }
/**
     * @return {Number}
     */
    getTestId() {
        return this.testId;
    }

    /**
     * @param {Number} testId
     */
    setTestId(testId) {
        this['testId'] = testId;
    }
/**
     * @return {module:model/QuestionCreate.QuestionTypeEnum}
     */
    getQuestionType() {
        return this.questionType;
    }

    /**
     * @param {module:model/QuestionCreate.QuestionTypeEnum} questionType
     */
    setQuestionType(questionType) {
        this['questionType'] = questionType;
    }
/**
     * @return {String}
     */
    getPicture() {
        return this.picture;
    }

    /**
     * @param {String} picture
     */
    setPicture(picture) {
        this['picture'] = picture;
    }
/**
     * @return {Number}
     */
    getTopicId() {
        return this.topicId;
    }

    /**
     * @param {Number} topicId
     */
    setTopicId(topicId) {
        this['topicId'] = topicId;
    }

}

QuestionCreate.RequiredProperties = ["text", "complexityPoints", "testId"];

/**
 * @member {String} text
 */
QuestionCreate.prototype['text'] = undefined;

/**
 * @member {Number} complexityPoints
 */
QuestionCreate.prototype['complexityPoints'] = undefined;

/**
 * @member {Number} testId
 */
QuestionCreate.prototype['testId'] = undefined;

/**
 * @member {module:model/QuestionCreate.QuestionTypeEnum} questionType
 */
QuestionCreate.prototype['questionType'] = undefined;

/**
 * @member {String} picture
 */
QuestionCreate.prototype['picture'] = undefined;

/**
 * @member {Number} topicId
 */
QuestionCreate.prototype['topicId'] = undefined;





/**
 * Allowed values for the <code>questionType</code> property.
 * @enum {String}
 * @readonly
 */
QuestionCreate['QuestionTypeEnum'] = {

    /**
     * value: "test"
     * @const
     */
    "test": "test",

    /**
     * value: "open"
     * @const
     */
    "open": "open"
};



export default QuestionCreate;

