/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RolePermissionRead model module.
 * @module model/RolePermissionRead
 * @version 0.1.0
 */
class RolePermissionRead {
    /**
     * Constructs a new <code>RolePermissionRead</code>.
     * @alias module:model/RolePermissionRead
     * @param id {Number} 
     * @param roleId {Number} 
     * @param permissionId {Number} 
     */
    constructor(id, roleId, permissionId) { 
        
        RolePermissionRead.initialize(this, id, roleId, permissionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, roleId, permissionId) { 
        obj['id'] = id;
        obj['roleId'] = roleId;
        obj['permissionId'] = permissionId;
    }

    /**
     * Constructs a <code>RolePermissionRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RolePermissionRead} obj Optional instance to populate.
     * @return {module:model/RolePermissionRead} The populated <code>RolePermissionRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RolePermissionRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'Number');
            }
            if (data.hasOwnProperty('permissionId')) {
                obj['permissionId'] = ApiClient.convertToType(data['permissionId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RolePermissionRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RolePermissionRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RolePermissionRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Number}
     */
    getRoleId() {
        return this.roleId;
    }

    /**
     * @param {Number} roleId
     */
    setRoleId(roleId) {
        this['roleId'] = roleId;
    }
/**
     * @return {Number}
     */
    getPermissionId() {
        return this.permissionId;
    }

    /**
     * @param {Number} permissionId
     */
    setPermissionId(permissionId) {
        this['permissionId'] = permissionId;
    }

}

RolePermissionRead.RequiredProperties = ["id", "roleId", "permissionId"];

/**
 * @member {Number} id
 */
RolePermissionRead.prototype['id'] = undefined;

/**
 * @member {Number} roleId
 */
RolePermissionRead.prototype['roleId'] = undefined;

/**
 * @member {Number} permissionId
 */
RolePermissionRead.prototype['permissionId'] = undefined;






export default RolePermissionRead;

