/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestCreate model module.
 * @module model/TestCreate
 * @version 0.1.0
 */
class TestCreate {
    /**
     * Constructs a new <code>TestCreate</code>.
     * @alias module:model/TestCreate
     * @param name {String} 
     * @param description {String} 
     * @param durationInMinutes {Number} 
     */
    constructor(name, description, durationInMinutes) { 
        
        TestCreate.initialize(this, name, description, durationInMinutes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, durationInMinutes) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['durationInMinutes'] = durationInMinutes;
    }

    /**
     * Constructs a <code>TestCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestCreate} obj Optional instance to populate.
     * @return {module:model/TestCreate} The populated <code>TestCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestCreate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('durationInMinutes')) {
                obj['durationInMinutes'] = ApiClient.convertToType(data['durationInMinutes'], 'Number');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

TestCreate.RequiredProperties = ["name", "description", "durationInMinutes"];

/**
 * @member {String} name
 */
TestCreate.prototype['name'] = undefined;

/**
 * @member {String} description
 */
TestCreate.prototype['description'] = undefined;

/**
 * @member {Number} durationInMinutes
 */
TestCreate.prototype['durationInMinutes'] = undefined;

/**
 * @member {Number} moduleId
 */
TestCreate.prototype['moduleId'] = undefined;

/**
 * @member {Number} courseId
 */
TestCreate.prototype['courseId'] = undefined;






export default TestCreate;

