/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestResultRead model module.
 * @module model/TestResultRead
 * @version 0.1.0
 */
class TestResultRead {
    /**
     * Constructs a new <code>TestResultRead</code>.
     * @alias module:model/TestResultRead
     * @param id {Number} 
     * @param scoreInPoints {Number} 
     * @param isPassed {Boolean} 
     * @param durationInMinutes {Number} 
     * @param result {Number} 
     * @param testId {Number} 
     * @param userId {Number} 
     */
    constructor(id, scoreInPoints, isPassed, durationInMinutes, result, testId, userId) { 
        
        TestResultRead.initialize(this, id, scoreInPoints, isPassed, durationInMinutes, result, testId, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, scoreInPoints, isPassed, durationInMinutes, result, testId, userId) { 
        obj['id'] = id;
        obj['scoreInPoints'] = scoreInPoints;
        obj['isPassed'] = isPassed;
        obj['durationInMinutes'] = durationInMinutes;
        obj['result'] = result;
        obj['testId'] = testId;
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>TestResultRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestResultRead} obj Optional instance to populate.
     * @return {module:model/TestResultRead} The populated <code>TestResultRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestResultRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('scoreInPoints')) {
                obj['scoreInPoints'] = ApiClient.convertToType(data['scoreInPoints'], 'Number');
            }
            if (data.hasOwnProperty('isPassed')) {
                obj['isPassed'] = ApiClient.convertToType(data['isPassed'], 'Boolean');
            }
            if (data.hasOwnProperty('durationInMinutes')) {
                obj['durationInMinutes'] = ApiClient.convertToType(data['durationInMinutes'], 'Number');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'Number');
            }
            if (data.hasOwnProperty('testId')) {
                obj['testId'] = ApiClient.convertToType(data['testId'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TestResultRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TestResultRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TestResultRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Number}
     */
    getScoreInPoints() {
        return this.scoreInPoints;
    }

    /**
     * @param {Number} scoreInPoints
     */
    setScoreInPoints(scoreInPoints) {
        this['scoreInPoints'] = scoreInPoints;
    }
/**
     * @return {Boolean}
     */
    getIsPassed() {
        return this.isPassed;
    }

    /**
     * @param {Boolean} isPassed
     */
    setIsPassed(isPassed) {
        this['isPassed'] = isPassed;
    }
/**
     * @return {Number}
     */
    getDurationInMinutes() {
        return this.durationInMinutes;
    }

    /**
     * @param {Number} durationInMinutes
     */
    setDurationInMinutes(durationInMinutes) {
        this['durationInMinutes'] = durationInMinutes;
    }
/**
     * @return {Number}
     */
    getResult() {
        return this.result;
    }

    /**
     * @param {Number} result
     */
    setResult(result) {
        this['result'] = result;
    }
/**
     * @return {Number}
     */
    getTestId() {
        return this.testId;
    }

    /**
     * @param {Number} testId
     */
    setTestId(testId) {
        this['testId'] = testId;
    }
/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }

}

TestResultRead.RequiredProperties = ["id", "scoreInPoints", "isPassed", "durationInMinutes", "result", "testId", "userId"];

/**
 * @member {Number} id
 */
TestResultRead.prototype['id'] = undefined;

/**
 * @member {Number} scoreInPoints
 */
TestResultRead.prototype['scoreInPoints'] = undefined;

/**
 * @member {Boolean} isPassed
 */
TestResultRead.prototype['isPassed'] = undefined;

/**
 * @member {Number} durationInMinutes
 */
TestResultRead.prototype['durationInMinutes'] = undefined;

/**
 * @member {Number} result
 */
TestResultRead.prototype['result'] = undefined;

/**
 * @member {Number} testId
 */
TestResultRead.prototype['testId'] = undefined;

/**
 * @member {Number} userId
 */
TestResultRead.prototype['userId'] = undefined;






export default TestResultRead;

