/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TopicContentRead model module.
 * @module model/TopicContentRead
 * @version 0.1.0
 */
class TopicContentRead {
    /**
     * Constructs a new <code>TopicContentRead</code>.
     * @alias module:model/TopicContentRead
     * @param id {Number} 
     * @param description {String} 
     * @param file {String} 
     * @param topicId {Number} 
     */
    constructor(id, description, file, topicId) { 
        
        TopicContentRead.initialize(this, id, description, file, topicId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, description, file, topicId) { 
        obj['id'] = id;
        obj['description'] = description;
        obj['file'] = file;
        obj['topicId'] = topicId;
    }

    /**
     * Constructs a <code>TopicContentRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopicContentRead} obj Optional instance to populate.
     * @return {module:model/TopicContentRead} The populated <code>TopicContentRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicContentRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('topicId')) {
                obj['topicId'] = ApiClient.convertToType(data['topicId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopicContentRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopicContentRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TopicContentRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['file'] && !(typeof data['file'] === 'string' || data['file'] instanceof String)) {
            throw new Error("Expected the field `file` to be a primitive type in the JSON string but got " + data['file']);
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getFile() {
        return this.file;
    }

    /**
     * @param {String} file
     */
    setFile(file) {
        this['file'] = file;
    }
/**
     * @return {Number}
     */
    getTopicId() {
        return this.topicId;
    }

    /**
     * @param {Number} topicId
     */
    setTopicId(topicId) {
        this['topicId'] = topicId;
    }

}

TopicContentRead.RequiredProperties = ["id", "description", "file", "topicId"];

/**
 * @member {Number} id
 */
TopicContentRead.prototype['id'] = undefined;

/**
 * @member {String} description
 */
TopicContentRead.prototype['description'] = undefined;

/**
 * @member {String} file
 */
TopicContentRead.prototype['file'] = undefined;

/**
 * @member {Number} topicId
 */
TopicContentRead.prototype['topicId'] = undefined;






export default TopicContentRead;

