/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TopicContentCreate model module.
 * @module model/TopicContentCreate
 * @version 0.1.0
 */
class TopicContentCreate {
    /**
     * Constructs a new <code>TopicContentCreate</code>.
     * @alias module:model/TopicContentCreate
     * @param description {String} 
     * @param file {String} 
     * @param topicId {Number} 
     */
    constructor(description, file, topicId) { 
        
        TopicContentCreate.initialize(this, description, file, topicId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, file, topicId) { 
        obj['description'] = description;
        obj['file'] = file;
        obj['topicId'] = topicId;
    }

    /**
     * Constructs a <code>TopicContentCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopicContentCreate} obj Optional instance to populate.
     * @return {module:model/TopicContentCreate} The populated <code>TopicContentCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicContentCreate();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('topicId')) {
                obj['topicId'] = ApiClient.convertToType(data['topicId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopicContentCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopicContentCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TopicContentCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['file'] && !(typeof data['file'] === 'string' || data['file'] instanceof String)) {
            throw new Error("Expected the field `file` to be a primitive type in the JSON string but got " + data['file']);
        }

        return true;
    }


}

TopicContentCreate.RequiredProperties = ["description", "file", "topicId"];

/**
 * @member {String} description
 */
TopicContentCreate.prototype['description'] = undefined;

/**
 * @member {String} file
 */
TopicContentCreate.prototype['file'] = undefined;

/**
 * @member {Number} topicId
 */
TopicContentCreate.prototype['topicId'] = undefined;






export default TopicContentCreate;

