/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TopicCreate model module.
 * @module model/TopicCreate
 * @version 0.1.0
 */
class TopicCreate {
    /**
     * Constructs a new <code>TopicCreate</code>.
     * @alias module:model/TopicCreate
     * @param name {String} 
     * @param description {String} 
     * @param moduleId {Number} 
     */
    constructor(name, description, moduleId) { 
        
        TopicCreate.initialize(this, name, description, moduleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, moduleId) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['moduleId'] = moduleId;
    }

    /**
     * Constructs a <code>TopicCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopicCreate} obj Optional instance to populate.
     * @return {module:model/TopicCreate} The populated <code>TopicCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicCreate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopicCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopicCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TopicCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * @param {String} name
     */
    setName(name) {
        this['name'] = name;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {Number}
     */
    getModuleId() {
        return this.moduleId;
    }

    /**
     * @param {Number} moduleId
     */
    setModuleId(moduleId) {
        this['moduleId'] = moduleId;
    }

}

TopicCreate.RequiredProperties = ["name", "description", "moduleId"];

/**
 * @member {String} name
 */
TopicCreate.prototype['name'] = undefined;

/**
 * @member {String} description
 */
TopicCreate.prototype['description'] = undefined;

/**
 * @member {Number} moduleId
 */
TopicCreate.prototype['moduleId'] = undefined;






export default TopicCreate;

