/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAnswerCreate model module.
 * @module model/UserAnswerCreate
 * @version 0.1.0
 */
class UserAnswerCreate {
    /**
     * Constructs a new <code>UserAnswerCreate</code>.
     * @alias module:model/UserAnswerCreate
     * @param userId {Number} 
     * @param testResultId {Number} 
     * @param questionId {Number} 
     * @param isCorrect {Boolean} 
     * @param timeSpentInMinutes {Number} 
     */
    constructor(userId, testResultId, questionId, isCorrect, timeSpentInMinutes) { 
        
        UserAnswerCreate.initialize(this, userId, testResultId, questionId, isCorrect, timeSpentInMinutes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, testResultId, questionId, isCorrect, timeSpentInMinutes) { 
        obj['userId'] = userId;
        obj['testResultId'] = testResultId;
        obj['questionId'] = questionId;
        obj['isCorrect'] = isCorrect;
        obj['timeSpentInMinutes'] = timeSpentInMinutes;
    }

    /**
     * Constructs a <code>UserAnswerCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAnswerCreate} obj Optional instance to populate.
     * @return {module:model/UserAnswerCreate} The populated <code>UserAnswerCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAnswerCreate();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('testResultId')) {
                obj['testResultId'] = ApiClient.convertToType(data['testResultId'], 'Number');
            }
            if (data.hasOwnProperty('questionId')) {
                obj['questionId'] = ApiClient.convertToType(data['questionId'], 'Number');
            }
            if (data.hasOwnProperty('isCorrect')) {
                obj['isCorrect'] = ApiClient.convertToType(data['isCorrect'], 'Boolean');
            }
            if (data.hasOwnProperty('timeSpentInMinutes')) {
                obj['timeSpentInMinutes'] = ApiClient.convertToType(data['timeSpentInMinutes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserAnswerCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserAnswerCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserAnswerCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }
/**
     * @return {Number}
     */
    getTestResultId() {
        return this.testResultId;
    }

    /**
     * @param {Number} testResultId
     */
    setTestResultId(testResultId) {
        this['testResultId'] = testResultId;
    }
/**
     * @return {Number}
     */
    getQuestionId() {
        return this.questionId;
    }

    /**
     * @param {Number} questionId
     */
    setQuestionId(questionId) {
        this['questionId'] = questionId;
    }
/**
     * @return {Boolean}
     */
    getIsCorrect() {
        return this.isCorrect;
    }

    /**
     * @param {Boolean} isCorrect
     */
    setIsCorrect(isCorrect) {
        this['isCorrect'] = isCorrect;
    }
/**
     * @return {Number}
     */
    getTimeSpentInMinutes() {
        return this.timeSpentInMinutes;
    }

    /**
     * @param {Number} timeSpentInMinutes
     */
    setTimeSpentInMinutes(timeSpentInMinutes) {
        this['timeSpentInMinutes'] = timeSpentInMinutes;
    }

}

UserAnswerCreate.RequiredProperties = ["userId", "testResultId", "questionId", "isCorrect", "timeSpentInMinutes"];

/**
 * @member {Number} userId
 */
UserAnswerCreate.prototype['userId'] = undefined;

/**
 * @member {Number} testResultId
 */
UserAnswerCreate.prototype['testResultId'] = undefined;

/**
 * @member {Number} questionId
 */
UserAnswerCreate.prototype['questionId'] = undefined;

/**
 * @member {Boolean} isCorrect
 */
UserAnswerCreate.prototype['isCorrect'] = undefined;

/**
 * @member {Number} timeSpentInMinutes
 */
UserAnswerCreate.prototype['timeSpentInMinutes'] = undefined;






export default UserAnswerCreate;

