/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserModuleKnowledgeRead model module.
 * @module model/UserModuleKnowledgeRead
 * @version 0.1.0
 */
class UserModuleKnowledgeRead {
    /**
     * Constructs a new <code>UserModuleKnowledgeRead</code>.
     * @alias module:model/UserModuleKnowledgeRead
     * @param id {Number} 
     * @param userId {Number} 
     * @param moduleId {Number} 
     * @param knowledge {Number} 
     * @param lastUpdated {Date} 
     */
    constructor(id, userId, moduleId, knowledge, lastUpdated) { 
        
        UserModuleKnowledgeRead.initialize(this, id, userId, moduleId, knowledge, lastUpdated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, userId, moduleId, knowledge, lastUpdated) { 
        obj['id'] = id;
        obj['userId'] = userId;
        obj['moduleId'] = moduleId;
        obj['knowledge'] = knowledge;
        obj['lastUpdated'] = lastUpdated;
    }

    /**
     * Constructs a <code>UserModuleKnowledgeRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserModuleKnowledgeRead} obj Optional instance to populate.
     * @return {module:model/UserModuleKnowledgeRead} The populated <code>UserModuleKnowledgeRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserModuleKnowledgeRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
            if (data.hasOwnProperty('knowledge')) {
                obj['knowledge'] = ApiClient.convertToType(data['knowledge'], 'Number');
            }
            if (data.hasOwnProperty('lastUpdated')) {
                obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserModuleKnowledgeRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserModuleKnowledgeRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserModuleKnowledgeRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }
/**
     * @return {Number}
     */
    getModuleId() {
        return this.moduleId;
    }

    /**
     * @param {Number} moduleId
     */
    setModuleId(moduleId) {
        this['moduleId'] = moduleId;
    }
/**
     * @return {Number}
     */
    getKnowledge() {
        return this.knowledge;
    }

    /**
     * @param {Number} knowledge
     */
    setKnowledge(knowledge) {
        this['knowledge'] = knowledge;
    }
/**
     * @return {Date}
     */
    getLastUpdated() {
        return this.lastUpdated;
    }

    /**
     * @param {Date} lastUpdated
     */
    setLastUpdated(lastUpdated) {
        this['lastUpdated'] = lastUpdated;
    }

}

UserModuleKnowledgeRead.RequiredProperties = ["id", "userId", "moduleId", "knowledge", "lastUpdated"];

/**
 * @member {Number} id
 */
UserModuleKnowledgeRead.prototype['id'] = undefined;

/**
 * @member {Number} userId
 */
UserModuleKnowledgeRead.prototype['userId'] = undefined;

/**
 * @member {Number} moduleId
 */
UserModuleKnowledgeRead.prototype['moduleId'] = undefined;

/**
 * @member {Number} knowledge
 */
UserModuleKnowledgeRead.prototype['knowledge'] = undefined;

/**
 * @member {Date} lastUpdated
 */
UserModuleKnowledgeRead.prototype['lastUpdated'] = undefined;






export default UserModuleKnowledgeRead;

