/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRead model module.
 * @module model/UserRead
 * @version 0.1.0
 */
class UserRead {
    /**
     * Constructs a new <code>UserRead</code>.
     * @alias module:model/UserRead
     * @param id {Number} 
     * @param login {String} 
     * @param name {String} 
     * @param surname {String} 
     * @param roleId {Number} 
     */
    constructor(id, login, name, surname, roleId) { 
        
        UserRead.initialize(this, id, login, name, surname, roleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, login, name, surname, roleId) { 
        obj['id'] = id;
        obj['login'] = login;
        obj['name'] = name;
        obj['surname'] = surname;
        obj['roleId'] = roleId;
    }

    /**
     * Constructs a <code>UserRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRead} obj Optional instance to populate.
     * @return {module:model/UserRead} The populated <code>UserRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('roleId')) {
                obj['roleId'] = ApiClient.convertToType(data['roleId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['login'] && !(typeof data['login'] === 'string' || data['login'] instanceof String)) {
            throw new Error("Expected the field `login` to be a primitive type in the JSON string but got " + data['login']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['surname'] && !(typeof data['surname'] === 'string' || data['surname'] instanceof String)) {
            throw new Error("Expected the field `surname` to be a primitive type in the JSON string but got " + data['surname']);
        }

        return true;
    }


}

UserRead.RequiredProperties = ["id", "login", "name", "surname", "roleId"];

/**
 * @member {Number} id
 */
UserRead.prototype['id'] = undefined;

/**
 * @member {String} login
 */
UserRead.prototype['login'] = undefined;

/**
 * @member {String} name
 */
UserRead.prototype['name'] = undefined;

/**
 * @member {String} surname
 */
UserRead.prototype['surname'] = undefined;

/**
 * @member {Number} roleId
 */
UserRead.prototype['roleId'] = undefined;






export default UserRead;

