/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserModuleKnowledgeCreate model module.
 * @module model/UserModuleKnowledgeCreate
 * @version 0.1.0
 */
class UserModuleKnowledgeCreate {
    /**
     * Constructs a new <code>UserModuleKnowledgeCreate</code>.
     * @alias module:model/UserModuleKnowledgeCreate
     * @param userId {Number} 
     * @param moduleId {Number} 
     * @param knowledge {Number} 
     */
    constructor(userId, moduleId, knowledge) { 
        
        UserModuleKnowledgeCreate.initialize(this, userId, moduleId, knowledge);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, moduleId, knowledge) { 
        obj['userId'] = userId;
        obj['moduleId'] = moduleId;
        obj['knowledge'] = knowledge;
    }

    /**
     * Constructs a <code>UserModuleKnowledgeCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserModuleKnowledgeCreate} obj Optional instance to populate.
     * @return {module:model/UserModuleKnowledgeCreate} The populated <code>UserModuleKnowledgeCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserModuleKnowledgeCreate();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
            if (data.hasOwnProperty('knowledge')) {
                obj['knowledge'] = ApiClient.convertToType(data['knowledge'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserModuleKnowledgeCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserModuleKnowledgeCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserModuleKnowledgeCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }
/**
     * @return {Number}
     */
    getModuleId() {
        return this.moduleId;
    }

    /**
     * @param {Number} moduleId
     */
    setModuleId(moduleId) {
        this['moduleId'] = moduleId;
    }
/**
     * @return {Number}
     */
    getKnowledge() {
        return this.knowledge;
    }

    /**
     * @param {Number} knowledge
     */
    setKnowledge(knowledge) {
        this['knowledge'] = knowledge;
    }

}

UserModuleKnowledgeCreate.RequiredProperties = ["userId", "moduleId", "knowledge"];

/**
 * @member {Number} userId
 */
UserModuleKnowledgeCreate.prototype['userId'] = undefined;

/**
 * @member {Number} moduleId
 */
UserModuleKnowledgeCreate.prototype['moduleId'] = undefined;

/**
 * @member {Number} knowledge
 */
UserModuleKnowledgeCreate.prototype['knowledge'] = undefined;






export default UserModuleKnowledgeCreate;

