/**
 * LMS Generic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCourseKnowledgeCreate model module.
 * @module model/UserCourseKnowledgeCreate
 * @version 0.1.0
 */
class UserCourseKnowledgeCreate {
    /**
     * Constructs a new <code>UserCourseKnowledgeCreate</code>.
     * @alias module:model/UserCourseKnowledgeCreate
     * @param userId {Number} 
     * @param courseId {Number} 
     * @param knowledge {Number} 
     */
    constructor(userId, courseId, knowledge) { 
        
        UserCourseKnowledgeCreate.initialize(this, userId, courseId, knowledge);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, courseId, knowledge) { 
        obj['userId'] = userId;
        obj['courseId'] = courseId;
        obj['knowledge'] = knowledge;
    }

    /**
     * Constructs a <code>UserCourseKnowledgeCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCourseKnowledgeCreate} obj Optional instance to populate.
     * @return {module:model/UserCourseKnowledgeCreate} The populated <code>UserCourseKnowledgeCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCourseKnowledgeCreate();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('courseId')) {
                obj['courseId'] = ApiClient.convertToType(data['courseId'], 'Number');
            }
            if (data.hasOwnProperty('knowledge')) {
                obj['knowledge'] = ApiClient.convertToType(data['knowledge'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCourseKnowledgeCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCourseKnowledgeCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserCourseKnowledgeCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getUserId() {
        return this.userId;
    }

    /**
     * @param {Number} userId
     */
    setUserId(userId) {
        this['userId'] = userId;
    }
/**
     * @return {Number}
     */
    getCourseId() {
        return this.courseId;
    }

    /**
     * @param {Number} courseId
     */
    setCourseId(courseId) {
        this['courseId'] = courseId;
    }
/**
     * @return {Number}
     */
    getKnowledge() {
        return this.knowledge;
    }

    /**
     * @param {Number} knowledge
     */
    setKnowledge(knowledge) {
        this['knowledge'] = knowledge;
    }

}

UserCourseKnowledgeCreate.RequiredProperties = ["userId", "courseId", "knowledge"];

/**
 * @member {Number} userId
 */
UserCourseKnowledgeCreate.prototype['userId'] = undefined;

/**
 * @member {Number} courseId
 */
UserCourseKnowledgeCreate.prototype['courseId'] = undefined;

/**
 * @member {Number} knowledge
 */
UserCourseKnowledgeCreate.prototype['knowledge'] = undefined;






export default UserCourseKnowledgeCreate;

